# Grace project file
#
version 50125
page size 792, 612
page scroll 5%
page inout 5%
link page off
map font 8 to "Courier", "Courier"
map font 10 to "Courier-Bold", "Courier-Bold"
map font 11 to "Courier-BoldOblique", "Courier-BoldOblique"
map font 9 to "Courier-Oblique", "Courier-Oblique"
map font 4 to "Helvetica", "Helvetica"
map font 6 to "Helvetica-Bold", "Helvetica-Bold"
map font 7 to "Helvetica-BoldOblique", "Helvetica-BoldOblique"
map font 5 to "Helvetica-Oblique", "Helvetica-Oblique"
map font 14 to "NimbusMonoL-BoldOblique", "NimbusMonoL-BoldOblique"
map font 15 to "NimbusMonoL-Regular", "NimbusMonoL-Regular"
map font 16 to "NimbusMonoL-RegularOblique", "NimbusMonoL-RegularOblique"
map font 30 to "NimbusMonoPS-BoldItalic", "NimbusMonoPS-BoldItalic"
map font 31 to "NimbusMonoPS-Italic", "NimbusMonoPS-Italic"
map font 32 to "NimbusMonoPS-Regular", "NimbusMonoPS-Regular"
map font 33 to "NimbusRoman-Bold", "NimbusRoman-Bold"
map font 34 to "NimbusRoman-BoldItalic", "NimbusRoman-BoldItalic"
map font 17 to "NimbusRomanNo9L-Medium", "NimbusRomanNo9L-Medium"
map font 18 to "NimbusRomanNo9L-MediumItalic", "NimbusRomanNo9L-MediumItalic"
map font 19 to "NimbusRomanNo9L-Regular", "NimbusRomanNo9L-Regular"
map font 20 to "NimbusRomanNo9L-RegularItalic", "NimbusRomanNo9L-RegularItalic"
map font 21 to "NimbusSansL-Bold", "NimbusSansL-Bold"
map font 22 to "NimbusSansL-BoldCondensed", "NimbusSansL-BoldCondensed"
map font 23 to "NimbusSansL-BoldCondensedItalic", "NimbusSansL-BoldCondensedItalic"
map font 24 to "NimbusSansL-BoldItalic", "NimbusSansL-BoldItalic"
map font 25 to "NimbusSansL-Regular", "NimbusSansL-Regular"
map font 26 to "NimbusSansL-RegularCondensed", "NimbusSansL-RegularCondensed"
map font 27 to "NimbusSansL-RegularCondensedItalic", "NimbusSansL-RegularCondensedItalic"
map font 28 to "NimbusSansL-RegularItalic", "NimbusSansL-RegularItalic"
map font 53 to "NimbusSansNarrow-Bold", "NimbusSansNarrow-Bold"
map font 54 to "NimbusSansNarrow-BoldOblique", "NimbusSansNarrow-BoldOblique"
map font 55 to "NimbusSansNarrow-Oblique", "NimbusSansNarrow-Oblique"
map font 56 to "NimbusSansNarrow-Regular", "NimbusSansNarrow-Regular"
map font 57 to "P052-Bold", "P052-Bold"
map font 58 to "P052-BoldItalic", "P052-BoldItalic"
map font 59 to "P052-Italic", "P052-Italic"
map font 60 to "P052-Roman", "P052-Roman"
map font 29 to "StandardSymbolsL-Regular", "StandardSymbolsL-Regular"
map font 62 to "StandardSymbolsPS-Regular", "StandardSymbolsPS-Regular"
map font 12 to "Symbol", "Symbol"
map font 2 to "Times-Bold", "Times-Bold"
map font 3 to "Times-BoldItalic", "Times-BoldItalic"
map font 1 to "Times-Italic", "Times-Italic"
map font 0 to "Times-Roman", "Times-Roman"
map font 68 to "URWBookman-Demi", "URWBookman-Demi"
map font 69 to "URWBookman-DemiItalic", "URWBookman-DemiItalic"
map font 70 to "URWBookman-Light", "URWBookman-Light"
map font 71 to "URWBookman-LightItalic", "URWBookman-LightItalic"
map font 35 to "URWBookmanL-DemiBold", "URWBookmanL-DemiBold"
map font 36 to "URWBookmanL-DemiBoldItalic", "URWBookmanL-DemiBoldItalic"
map font 37 to "URWBookmanL-Light", "URWBookmanL-Light"
map font 38 to "URWBookmanL-LightItalic", "URWBookmanL-LightItalic"
map font 39 to "URWChanceryL-MediumItalic", "URWChanceryL-MediumItalic"
map font 77 to "URWGothic-Book", "URWGothic-Book"
map font 78 to "URWGothic-BookOblique", "URWGothic-BookOblique"
map font 79 to "URWGothic-Demi", "URWGothic-Demi"
map font 80 to "URWGothic-DemiOblique", "URWGothic-DemiOblique"
map font 40 to "URWGothicL-Book", "URWGothicL-Book"
map font 41 to "URWGothicL-BookOblique", "URWGothicL-BookOblique"
map font 42 to "URWGothicL-Demi", "URWGothicL-Demi"
map font 43 to "URWGothicL-DemiOblique", "URWGothicL-DemiOblique"
map font 44 to "URWPalladioL-Bold", "URWPalladioL-Bold"
map font 45 to "URWPalladioL-BoldItalic", "URWPalladioL-BoldItalic"
map font 46 to "URWPalladioL-Italic", "URWPalladioL-Italic"
map font 47 to "URWPalladioL-Roman", "URWPalladioL-Roman"
map font 89 to "Utopia-Bold", "Utopia-Bold"
map font 90 to "Utopia-BoldItalic", "Utopia-BoldItalic"
map font 91 to "Utopia-Italic", "Utopia-Italic"
map font 92 to "Utopia-Regular", "Utopia-Regular"
map font 93 to "Z003-MediumItalic", "Z003-MediumItalic"
map font 13 to "ZapfDingbats", "ZapfDingbats"
map color 0 to (255, 255, 255), "white"
map color 1 to (0, 0, 0), "black"
map color 2 to (255, 0, 0), "red"
map color 3 to (0, 255, 0), "green"
map color 4 to (0, 0, 255), "blue"
map color 5 to (255, 255, 0), "yellow"
map color 6 to (188, 143, 143), "brown"
map color 7 to (110, 110, 110), "grey"
map color 8 to (148, 0, 211), "violet"
map color 9 to (0, 255, 255), "cyan"
map color 10 to (255, 0, 255), "magenta"
map color 11 to (255, 165, 0), "orange"
map color 12 to (114, 33, 188), "indigo"
map color 13 to (103, 7, 72), "maroon"
map color 14 to (64, 224, 208), "turquoise"
map color 15 to (0, 139, 0), "green4"
map color 16 to (225, 225, 225), "grey1"
reference date 0
date wrap off
date wrap year 1950
default linewidth 1.0
default linestyle 1
default color 1
default pattern 1
default font 0
default char size 1.000000
default symbol size 1.000000
default sformat "%.8g"
background color 0
page background fill on
timestamp off
timestamp 0.03, 0.03
timestamp color 1
timestamp rot 0
timestamp font 0
timestamp char size 1.000000
timestamp def "Sat Jul  2 22:19:01 2022"
with string
    string on
    string loctype view
    string 0.07, 0.95
    string color 1
    string rot 0
    string font 6
    string just 0
    string char size 1.000000
    string def "B"
with string
    string on
    string loctype view
    string 0.44, 0.96
    string color 1
    string rot 0
    string font 6
    string just 0
    string char size 1.000000
    string def "C"
with string
    string on
    string loctype view
    string 0.07, 0.72
    string color 1
    string rot 0
    string font 6
    string just 0
    string char size 1.000000
    string def "D"
with string
    string on
    string loctype view
    string 0.44, 0.72
    string color 1
    string rot 0
    string font 6
    string just 0
    string char size 1.000000
    string def "E"
with string
    string on
    string loctype view
    string 0.07, 0.49
    string color 1
    string rot 0
    string font 6
    string just 0
    string char size 1.000000
    string def "F"
with string
    string on
    string loctype view
    string 0.44, 0.49
    string color 1
    string rot 0
    string font 6
    string just 0
    string char size 1.000000
    string def "G"
with string
    string on
    string loctype view
    string 0.07, 0.26
    string color 1
    string rot 0
    string font 6
    string just 0
    string char size 1.000000
    string def "H"
with string
    string on
    string loctype view
    string 0.44, 0.26
    string color 1
    string rot 0
    string font 6
    string just 0
    string char size 1.000000
    string def "I"
with string
    string on
    string loctype view
    string 0.197, 0.945
    string color 1
    string rot 0
    string font 4
    string just 0
    string char size 0.800000
    string def "Osc"
with string
    string on
    string loctype view
    string 0.3, 0.945
    string color 1
    string rot 0
    string font 4
    string just 0
    string char size 0.800000
    string def "Bistable"
with string
    string on
    string loctype view
    string 0.145, 0.945
    string color 1
    string rot 0
    string font 4
    string just 0
    string char size 0.800000
    string def "Unif"
r0 off
link r0 to g0
r0 type above
r0 linestyle 1
r0 linewidth 1.0
r0 color 1
r0 line 0, 0, 0, 0
r1 off
link r1 to g0
r1 type above
r1 linestyle 1
r1 linewidth 1.0
r1 color 1
r1 line 0, 0, 0, 0
r2 off
link r2 to g0
r2 type above
r2 linestyle 1
r2 linewidth 1.0
r2 color 1
r2 line 0, 0, 0, 0
r3 off
link r3 to g0
r3 type above
r3 linestyle 1
r3 linewidth 1.0
r3 color 1
r3 line 0, 0, 0, 0
r4 off
link r4 to g0
r4 type above
r4 linestyle 1
r4 linewidth 1.0
r4 color 1
r4 line 0, 0, 0, 0
g0 on
g0 hidden false
g0 type XY
g0 stacked false
g0 bar hgap 0.000000
g0 fixedpoint off
g0 fixedpoint type 0
g0 fixedpoint xy 0.000000, 0.000000
g0 fixedpoint format general general
g0 fixedpoint prec 6, 6
with g0
    world 0, 0, 0.84, 0.6
    stack world 0, 0, 0, 0
    znorm 1
    view 0.150000, 0.020000, 0.400000, 0.970000
    title ""
    title font 0
    title size 1.500000
    title color 1
    subtitle ""
    subtitle font 0
    subtitle size 1.000000
    subtitle color 1
    xaxes scale Normal
    yaxes scale Normal
    xaxes invert off
    yaxes invert off
    xaxis  off
    yaxis  off
    altxaxis  off
    altyaxis  off
    legend on
    legend loctype view
    legend 0.69, 0.9
    legend box color 1
    legend box pattern 1
    legend box linewidth 1.0
    legend box linestyle 1
    legend box fill color 0
    legend box fill pattern 1
    legend font 0
    legend char size 1.000000
    legend color 1
    legend length 4
    legend vgap 1
    legend hgap 1
    legend invert false
    frame type 1
    frame linestyle 1
    frame linewidth 1.0
    frame color 1
    frame pattern 0
    frame background color 0
    frame background pattern 0
    s0 hidden false
    s0 type xy
    s0 symbol 0
    s0 symbol size 0.210000
    s0 symbol color 1
    s0 symbol pattern 1
    s0 symbol fill color 1
    s0 symbol fill pattern 1
    s0 symbol linewidth 1.0
    s0 symbol linestyle 1
    s0 symbol char 65
    s0 symbol char font 0
    s0 symbol skip 0
    s0 line type 0
    s0 line linestyle 1
    s0 line linewidth 1.0
    s0 line color 1
    s0 line pattern 1
    s0 baseline type 0
    s0 baseline off
    s0 dropline off
    s0 fill type 0
    s0 fill rule 0
    s0 fill color 1
    s0 fill pattern 1
    s0 avalue off
    s0 avalue type 2
    s0 avalue char size 1.000000
    s0 avalue font 0
    s0 avalue color 1
    s0 avalue rot 0
    s0 avalue format general
    s0 avalue prec 3
    s0 avalue prepend ""
    s0 avalue append ""
    s0 avalue offset 0.000000 , 0.000000
    s0 errorbar on
    s0 errorbar place both
    s0 errorbar color 1
    s0 errorbar pattern 1
    s0 errorbar size 0.170000
    s0 errorbar linewidth 1.0
    s0 errorbar linestyle 1
    s0 errorbar riser linewidth 1.0
    s0 errorbar riser linestyle 1
    s0 errorbar riser clip off
    s0 errorbar riser clip length 0.100000
    s0 comment "c227/tperst.col"
    s0 legend  ""
    s1 hidden false
    s1 type xy
    s1 symbol 0
    s1 symbol size 0.160000
    s1 symbol color 1
    s1 symbol pattern 1
    s1 symbol fill color 1
    s1 symbol fill pattern 0
    s1 symbol linewidth 1.0
    s1 symbol linestyle 1
    s1 symbol char 65
    s1 symbol char font 0
    s1 symbol skip 0
    s1 line type 1
    s1 line linestyle 1
    s1 line linewidth 1.0
    s1 line color 1
    s1 line pattern 1
    s1 baseline type 0
    s1 baseline off
    s1 dropline off
    s1 fill type 0
    s1 fill rule 0
    s1 fill color 1
    s1 fill pattern 1
    s1 avalue off
    s1 avalue type 2
    s1 avalue char size 1.000000
    s1 avalue font 0
    s1 avalue color 1
    s1 avalue rot 0
    s1 avalue format general
    s1 avalue prec 3
    s1 avalue prepend ""
    s1 avalue append ""
    s1 avalue offset 0.000000 , 0.000000
    s1 errorbar on
    s1 errorbar place both
    s1 errorbar color 1
    s1 errorbar pattern 1
    s1 errorbar size 1.000000
    s1 errorbar linewidth 1.0
    s1 errorbar linestyle 1
    s1 errorbar riser linewidth 1.0
    s1 errorbar riser linestyle 1
    s1 errorbar riser clip off
    s1 errorbar riser clip length 0.100000
    s1 comment "dat_qsub/no_pb_x_ginter_no_intra/arrows.xx"
    s1 legend  ""
    s2 hidden false
    s2 type xy
    s2 symbol 0
    s2 symbol size 0.160000
    s2 symbol color 1
    s2 symbol pattern 1
    s2 symbol fill color 1
    s2 symbol fill pattern 0
    s2 symbol linewidth 1.0
    s2 symbol linestyle 1
    s2 symbol char 65
    s2 symbol char font 0
    s2 symbol skip 0
    s2 line type 0
    s2 line linestyle 1
    s2 line linewidth 1.0
    s2 line color 1
    s2 line pattern 1
    s2 baseline type 0
    s2 baseline off
    s2 dropline off
    s2 fill type 0
    s2 fill rule 0
    s2 fill color 1
    s2 fill pattern 1
    s2 avalue off
    s2 avalue type 2
    s2 avalue char size 1.000000
    s2 avalue font 0
    s2 avalue color 1
    s2 avalue rot 0
    s2 avalue format general
    s2 avalue prec 3
    s2 avalue prepend ""
    s2 avalue append ""
    s2 avalue offset 0.000000 , 0.000000
    s2 errorbar on
    s2 errorbar place both
    s2 errorbar color 1
    s2 errorbar pattern 1
    s2 errorbar size 1.000000
    s2 errorbar linewidth 1.0
    s2 errorbar linestyle 1
    s2 errorbar riser linewidth 1.0
    s2 errorbar riser linestyle 1
    s2 errorbar riser clip off
    s2 errorbar riser clip length 0.100000
    s2 comment "dat_qsub/no_pb_x_ginter_no_intra/arrows.xx"
    s2 legend  ""
    s3 hidden false
    s3 type xy
    s3 symbol 0
    s3 symbol size 0.160000
    s3 symbol color 1
    s3 symbol pattern 1
    s3 symbol fill color 1
    s3 symbol fill pattern 1
    s3 symbol linewidth 1.0
    s3 symbol linestyle 1
    s3 symbol char 65
    s3 symbol char font 0
    s3 symbol skip 0
    s3 line type 1
    s3 line linestyle 1
    s3 line linewidth 1.0
    s3 line color 1
    s3 line pattern 1
    s3 baseline type 0
    s3 baseline off
    s3 dropline off
    s3 fill type 0
    s3 fill rule 0
    s3 fill color 1
    s3 fill pattern 1
    s3 avalue off
    s3 avalue type 2
    s3 avalue char size 1.000000
    s3 avalue font 0
    s3 avalue color 1
    s3 avalue rot 0
    s3 avalue format general
    s3 avalue prec 3
    s3 avalue prepend ""
    s3 avalue append ""
    s3 avalue offset 0.000000 , 0.000000
    s3 errorbar on
    s3 errorbar place both
    s3 errorbar color 1
    s3 errorbar pattern 1
    s3 errorbar size 1.000000
    s3 errorbar linewidth 1.0
    s3 errorbar linestyle 1
    s3 errorbar riser linewidth 1.0
    s3 errorbar riser linestyle 1
    s3 errorbar riser clip off
    s3 errorbar riser clip length 0.100000
    s3 comment "dat_qsub/no_pb_x_ginter_no_intra/arrows.xx"
    s3 legend  ""
    s4 hidden false
    s4 type xy
    s4 symbol 0
    s4 symbol size 1.000000
    s4 symbol color 16
    s4 symbol pattern 0
    s4 symbol fill color 11
    s4 symbol fill pattern 1
    s4 symbol linewidth 1.0
    s4 symbol linestyle 1
    s4 symbol char 65
    s4 symbol char font 0
    s4 symbol skip 0
    s4 line type 1
    s4 line linestyle 1
    s4 line linewidth 0.5
    s4 line color 16
    s4 line pattern 1
    s4 baseline type 0
    s4 baseline off
    s4 dropline off
    s4 fill type 1
    s4 fill rule 0
    s4 fill color 16
    s4 fill pattern 1
    s4 avalue off
    s4 avalue type 2
    s4 avalue char size 1.000000
    s4 avalue font 0
    s4 avalue color 1
    s4 avalue rot 0
    s4 avalue format general
    s4 avalue prec 3
    s4 avalue prepend ""
    s4 avalue append ""
    s4 avalue offset 0.000000 , 0.000000
    s4 errorbar on
    s4 errorbar place both
    s4 errorbar color 16
    s4 errorbar pattern 1
    s4 errorbar size 1.000000
    s4 errorbar linewidth 1.0
    s4 errorbar linestyle 1
    s4 errorbar riser linewidth 1.0
    s4 errorbar riser linestyle 1
    s4 errorbar riser clip off
    s4 errorbar riser clip length 0.100000
    s4 comment "dat_qsub/no_pb_x_ginter_no_intra/arrows.xx"
    s4 legend  ""
g1 on
g1 hidden false
g1 type XY
g1 stacked false
g1 bar hgap 0.000000
g1 fixedpoint off
g1 fixedpoint type 0
g1 fixedpoint xy 0.000000, 0.000000
g1 fixedpoint format general general
g1 fixedpoint prec 6, 6
with g1
    world 0, 0, 21, 1
    stack world 0, 0, 0, 0
    znorm 1
    view 0.150000, 0.759000, 0.400000, 0.779000
    title ""
    title font 0
    title size 1.500000
    title color 1
    subtitle ""
    subtitle font 0
    subtitle size 1.000000
    subtitle color 1
    xaxes scale Normal
    yaxes scale Normal
    xaxes invert off
    yaxes invert off
    xaxis  off
    yaxis  off
    altxaxis  off
    altyaxis  off
    legend on
    legend loctype view
    legend 0.69, 0.9
    legend box color 1
    legend box pattern 1
    legend box linewidth 1.0
    legend box linestyle 1
    legend box fill color 0
    legend box fill pattern 1
    legend font 0
    legend char size 1.000000
    legend color 1
    legend length 4
    legend vgap 1
    legend hgap 1
    legend invert false
    frame type 1
    frame linestyle 1
    frame linewidth 1.0
    frame color 1
    frame pattern 0
    frame background color 0
    frame background pattern 0
    s0 hidden false
    s0 type xy
    s0 symbol 0
    s0 symbol size 0.210000
    s0 symbol color 1
    s0 symbol pattern 1
    s0 symbol fill color 1
    s0 symbol fill pattern 1
    s0 symbol linewidth 1.0
    s0 symbol linestyle 1
    s0 symbol char 65
    s0 symbol char font 0
    s0 symbol skip 0
    s0 line type 0
    s0 line linestyle 1
    s0 line linewidth 1.0
    s0 line color 1
    s0 line pattern 1
    s0 baseline type 0
    s0 baseline off
    s0 dropline off
    s0 fill type 0
    s0 fill rule 0
    s0 fill color 1
    s0 fill pattern 1
    s0 avalue off
    s0 avalue type 2
    s0 avalue char size 1.000000
    s0 avalue font 0
    s0 avalue color 1
    s0 avalue rot 0
    s0 avalue format general
    s0 avalue prec 3
    s0 avalue prepend ""
    s0 avalue append ""
    s0 avalue offset 0.000000 , 0.000000
    s0 errorbar on
    s0 errorbar place both
    s0 errorbar color 1
    s0 errorbar pattern 1
    s0 errorbar size 0.170000
    s0 errorbar linewidth 1.0
    s0 errorbar linestyle 1
    s0 errorbar riser linewidth 1.0
    s0 errorbar riser linestyle 1
    s0 errorbar riser clip off
    s0 errorbar riser clip length 0.100000
    s0 comment "c227/tperst.col"
    s0 legend  ""
    s1 hidden false
    s1 type xy
    s1 symbol 0
    s1 symbol size 0.160000
    s1 symbol color 1
    s1 symbol pattern 1
    s1 symbol fill color 1
    s1 symbol fill pattern 0
    s1 symbol linewidth 1.0
    s1 symbol linestyle 1
    s1 symbol char 65
    s1 symbol char font 0
    s1 symbol skip 0
    s1 line type 1
    s1 line linestyle 1
    s1 line linewidth 1.0
    s1 line color 1
    s1 line pattern 1
    s1 baseline type 0
    s1 baseline off
    s1 dropline off
    s1 fill type 0
    s1 fill rule 0
    s1 fill color 1
    s1 fill pattern 1
    s1 avalue off
    s1 avalue type 2
    s1 avalue char size 1.000000
    s1 avalue font 0
    s1 avalue color 1
    s1 avalue rot 0
    s1 avalue format general
    s1 avalue prec 3
    s1 avalue prepend ""
    s1 avalue append ""
    s1 avalue offset 0.000000 , 0.000000
    s1 errorbar on
    s1 errorbar place both
    s1 errorbar color 1
    s1 errorbar pattern 1
    s1 errorbar size 1.000000
    s1 errorbar linewidth 1.0
    s1 errorbar linestyle 1
    s1 errorbar riser linewidth 1.0
    s1 errorbar riser linestyle 1
    s1 errorbar riser clip off
    s1 errorbar riser clip length 0.100000
    s1 comment "dat_qsub/no_pb_x_ginter_no_intra/arrows.xx"
    s1 legend  ""
    s2 hidden false
    s2 type xy
    s2 symbol 0
    s2 symbol size 0.160000
    s2 symbol color 1
    s2 symbol pattern 1
    s2 symbol fill color 1
    s2 symbol fill pattern 0
    s2 symbol linewidth 1.0
    s2 symbol linestyle 1
    s2 symbol char 65
    s2 symbol char font 0
    s2 symbol skip 0
    s2 line type 0
    s2 line linestyle 1
    s2 line linewidth 1.0
    s2 line color 1
    s2 line pattern 1
    s2 baseline type 0
    s2 baseline off
    s2 dropline off
    s2 fill type 0
    s2 fill rule 0
    s2 fill color 1
    s2 fill pattern 1
    s2 avalue off
    s2 avalue type 2
    s2 avalue char size 1.000000
    s2 avalue font 0
    s2 avalue color 1
    s2 avalue rot 0
    s2 avalue format general
    s2 avalue prec 3
    s2 avalue prepend ""
    s2 avalue append ""
    s2 avalue offset 0.000000 , 0.000000
    s2 errorbar on
    s2 errorbar place both
    s2 errorbar color 1
    s2 errorbar pattern 1
    s2 errorbar size 1.000000
    s2 errorbar linewidth 1.0
    s2 errorbar linestyle 1
    s2 errorbar riser linewidth 1.0
    s2 errorbar riser linestyle 1
    s2 errorbar riser clip off
    s2 errorbar riser clip length 0.100000
    s2 comment "dat_qsub/no_pb_x_ginter_no_intra/arrows.xx"
    s2 legend  ""
    s3 hidden false
    s3 type xy
    s3 symbol 0
    s3 symbol size 0.160000
    s3 symbol color 1
    s3 symbol pattern 1
    s3 symbol fill color 1
    s3 symbol fill pattern 1
    s3 symbol linewidth 1.0
    s3 symbol linestyle 1
    s3 symbol char 65
    s3 symbol char font 0
    s3 symbol skip 0
    s3 line type 0
    s3 line linestyle 1
    s3 line linewidth 1.0
    s3 line color 1
    s3 line pattern 1
    s3 baseline type 0
    s3 baseline off
    s3 dropline off
    s3 fill type 0
    s3 fill rule 0
    s3 fill color 1
    s3 fill pattern 1
    s3 avalue off
    s3 avalue type 2
    s3 avalue char size 1.000000
    s3 avalue font 0
    s3 avalue color 1
    s3 avalue rot 0
    s3 avalue format general
    s3 avalue prec 3
    s3 avalue prepend ""
    s3 avalue append ""
    s3 avalue offset 0.000000 , 0.000000
    s3 errorbar on
    s3 errorbar place both
    s3 errorbar color 1
    s3 errorbar pattern 1
    s3 errorbar size 1.000000
    s3 errorbar linewidth 1.0
    s3 errorbar linestyle 1
    s3 errorbar riser linewidth 1.0
    s3 errorbar riser linestyle 1
    s3 errorbar riser clip off
    s3 errorbar riser clip length 0.100000
    s3 comment "dat_qsub/no_pb_x_ginter_no_intra/arrows.xx"
    s3 legend  ""
    s4 hidden false
    s4 type xy
    s4 symbol 0
    s4 symbol size 1.000000
    s4 symbol color 2
    s4 symbol pattern 1
    s4 symbol fill color 2
    s4 symbol fill pattern 0
    s4 symbol linewidth 1.0
    s4 symbol linestyle 1
    s4 symbol char 65
    s4 symbol char font 0
    s4 symbol skip 0
    s4 line type 0
    s4 line linestyle 1
    s4 line linewidth 1.0
    s4 line color 2
    s4 line pattern 1
    s4 baseline type 0
    s4 baseline off
    s4 dropline off
    s4 fill type 0
    s4 fill rule 0
    s4 fill color 1
    s4 fill pattern 1
    s4 avalue off
    s4 avalue type 2
    s4 avalue char size 1.000000
    s4 avalue font 0
    s4 avalue color 1
    s4 avalue rot 0
    s4 avalue format general
    s4 avalue prec 3
    s4 avalue prepend ""
    s4 avalue append ""
    s4 avalue offset 0.000000 , 0.000000
    s4 errorbar on
    s4 errorbar place both
    s4 errorbar color 2
    s4 errorbar pattern 1
    s4 errorbar size 1.000000
    s4 errorbar linewidth 1.0
    s4 errorbar linestyle 1
    s4 errorbar riser linewidth 1.0
    s4 errorbar riser linestyle 1
    s4 errorbar riser clip off
    s4 errorbar riser clip length 0.100000
    s4 comment "dat_qsub/no_pb_x_ginter_no_intra/arrows.xx"
    s4 legend  ""
g2 on
g2 hidden false
g2 type XY
g2 stacked false
g2 bar hgap 0.000000
g2 fixedpoint off
g2 fixedpoint type 0
g2 fixedpoint xy 0.000000, 0.000000
g2 fixedpoint format general general
g2 fixedpoint prec 6, 6
with g2
    world 0, -0.5, 0.84, 90
    stack world 0, 0, 0, 0
    znorm 1
    view 0.150000, 0.780000, 0.400000, 0.940000
    title ""
    title font 0
    title size 1.500000
    title color 1
    subtitle ""
    subtitle font 0
    subtitle size 1.000000
    subtitle color 1
    xaxes scale Normal
    yaxes scale Normal
    xaxes invert off
    yaxes invert off
    xaxis  on
    xaxis  type zero false
    xaxis  offset 0.000000 , 0.000000
    xaxis  bar on
    xaxis  bar color 1
    xaxis  bar linestyle 1
    xaxis  bar linewidth 1.0
    xaxis  label ""
    xaxis  label layout para
    xaxis  label place auto
    xaxis  label char size 1.000000
    xaxis  label font 4
    xaxis  label color 1
    xaxis  label place normal
    xaxis  tick on
    xaxis  tick major 10
    xaxis  tick minor ticks 4
    xaxis  tick default 6
    xaxis  tick place rounded true
    xaxis  tick out
    xaxis  tick major size 0.460000
    xaxis  tick major color 1
    xaxis  tick major linewidth 1.0
    xaxis  tick major linestyle 1
    xaxis  tick major grid off
    xaxis  tick minor color 1
    xaxis  tick minor linewidth 1.0
    xaxis  tick minor linestyle 1
    xaxis  tick minor grid off
    xaxis  tick minor size 0.200000
    xaxis  ticklabel on
    xaxis  ticklabel format general
    xaxis  ticklabel prec 5
    xaxis  ticklabel formula ""
    xaxis  ticklabel append ""
    xaxis  ticklabel prepend ""
    xaxis  ticklabel angle 0
    xaxis  ticklabel skip 0
    xaxis  ticklabel stagger 0
    xaxis  ticklabel place normal
    xaxis  ticklabel offset auto
    xaxis  ticklabel offset 0.000000 , 0.010000
    xaxis  ticklabel start type spec
    xaxis  ticklabel start 2000.000000
    xaxis  ticklabel stop type auto
    xaxis  ticklabel stop 0.000000
    xaxis  ticklabel char size 1.000000
    xaxis  ticklabel font 4
    xaxis  ticklabel color 1
    xaxis  tick place normal
    xaxis  tick spec type none
    yaxis  on
    yaxis  type zero false
    yaxis  offset 0.000000 , 0.000000
    yaxis  bar on
    yaxis  bar color 1
    yaxis  bar linestyle 1
    yaxis  bar linewidth 1.0
    yaxis  label "Firing rate,\n\v{-0.3}<M>\si\N (1/s)"
    yaxis  label layout para
    yaxis  label place spec
    yaxis  label place 0.000000, 0.083000
    yaxis  label char size 0.800000
    yaxis  label font 4
    yaxis  label color 1
    yaxis  label place normal
    yaxis  tick on
    yaxis  tick major 30
    yaxis  tick minor ticks 2
    yaxis  tick default 6
    yaxis  tick place rounded true
    yaxis  tick out
    yaxis  tick major size 0.460000
    yaxis  tick major color 1
    yaxis  tick major linewidth 1.0
    yaxis  tick major linestyle 1
    yaxis  tick major grid off
    yaxis  tick minor color 1
    yaxis  tick minor linewidth 1.0
    yaxis  tick minor linestyle 1
    yaxis  tick minor grid off
    yaxis  tick minor size 0.200000
    yaxis  ticklabel on
    yaxis  ticklabel format general
    yaxis  ticklabel prec 5
    yaxis  ticklabel formula ""
    yaxis  ticklabel append ""
    yaxis  ticklabel prepend ""
    yaxis  ticklabel angle 0
    yaxis  ticklabel skip 0
    yaxis  ticklabel stagger 0
    yaxis  ticklabel place normal
    yaxis  ticklabel offset auto
    yaxis  ticklabel offset 0.000000 , 0.010000
    yaxis  ticklabel start type auto
    yaxis  ticklabel start 0.000000
    yaxis  ticklabel stop type auto
    yaxis  ticklabel stop 0.000000
    yaxis  ticklabel char size 0.800000
    yaxis  ticklabel font 4
    yaxis  ticklabel color 1
    yaxis  tick place normal
    yaxis  tick spec type none
    altxaxis  off
    altyaxis  off
    legend on
    legend loctype view
    legend 0.54, 0.83
    legend box color 1
    legend box pattern 0
    legend box linewidth 1.0
    legend box linestyle 0
    legend box fill color 0
    legend box fill pattern 1
    legend font 4
    legend char size 0.780000
    legend color 1
    legend length 3
    legend vgap 1
    legend hgap 1
    legend invert false
    frame type 1
    frame linestyle 1
    frame linewidth 1.0
    frame color 1
    frame pattern 1
    frame background color 0
    frame background pattern 0
    s0 hidden false
    s0 type xydy
    s0 symbol 1
    s0 symbol size 0.210000
    s0 symbol color 1
    s0 symbol pattern 1
    s0 symbol fill color 1
    s0 symbol fill pattern 1
    s0 symbol linewidth 1.0
    s0 symbol linestyle 1
    s0 symbol char 65
    s0 symbol char font 0
    s0 symbol skip 0
    s0 line type 0
    s0 line linestyle 1
    s0 line linewidth 1.0
    s0 line color 1
    s0 line pattern 1
    s0 baseline type 0
    s0 baseline off
    s0 dropline off
    s0 fill type 0
    s0 fill rule 0
    s0 fill color 1
    s0 fill pattern 1
    s0 avalue off
    s0 avalue type 2
    s0 avalue char size 1.000000
    s0 avalue font 0
    s0 avalue color 1
    s0 avalue rot 0
    s0 avalue format general
    s0 avalue prec 3
    s0 avalue prepend ""
    s0 avalue append ""
    s0 avalue offset 0.000000 , 0.000000
    s0 errorbar on
    s0 errorbar place both
    s0 errorbar color 1
    s0 errorbar pattern 1
    s0 errorbar size 0.170000
    s0 errorbar linewidth 1.0
    s0 errorbar linestyle 1
    s0 errorbar riser linewidth 1.0
    s0 errorbar riser linestyle 1
    s0 errorbar riser clip off
    s0 errorbar riser clip length 0.100000
    s0 comment "c227/tperst.col"
    s0 legend  ""
    s1 hidden false
    s1 type xydy
    s1 symbol 1
    s1 symbol size 0.210000
    s1 symbol color 7
    s1 symbol pattern 1
    s1 symbol fill color 7
    s1 symbol fill pattern 0
    s1 symbol linewidth 1.0
    s1 symbol linestyle 1
    s1 symbol char 65
    s1 symbol char font 0
    s1 symbol skip 0
    s1 line type 0
    s1 line linestyle 1
    s1 line linewidth 1.0
    s1 line color 1
    s1 line pattern 1
    s1 baseline type 0
    s1 baseline off
    s1 dropline off
    s1 fill type 0
    s1 fill rule 0
    s1 fill color 1
    s1 fill pattern 1
    s1 avalue off
    s1 avalue type 2
    s1 avalue char size 1.000000
    s1 avalue font 0
    s1 avalue color 1
    s1 avalue rot 0
    s1 avalue format general
    s1 avalue prec 3
    s1 avalue prepend ""
    s1 avalue append ""
    s1 avalue offset 0.000000 , 0.000000
    s1 errorbar on
    s1 errorbar place both
    s1 errorbar color 7
    s1 errorbar pattern 1
    s1 errorbar size 0.170000
    s1 errorbar linewidth 1.0
    s1 errorbar linestyle 1
    s1 errorbar riser linewidth 1.0
    s1 errorbar riser linestyle 1
    s1 errorbar riser clip off
    s1 errorbar riser clip length 0.100000
    s1 comment "c2281/mtper.mfr"
    s1 legend  ""
    s2 hidden false
    s2 type xy
    s2 symbol 0
    s2 symbol size 1.000000
    s2 symbol color 11
    s2 symbol pattern 1
    s2 symbol fill color 11
    s2 symbol fill pattern 0
    s2 symbol linewidth 1.0
    s2 symbol linestyle 1
    s2 symbol char 65
    s2 symbol char font 0
    s2 symbol skip 0
    s2 line type 1
    s2 line linestyle 1
    s2 line linewidth 1.5
    s2 line color 11
    s2 line pattern 1
    s2 baseline type 0
    s2 baseline off
    s2 dropline off
    s2 fill type 0
    s2 fill rule 0
    s2 fill color 1
    s2 fill pattern 1
    s2 avalue off
    s2 avalue type 2
    s2 avalue char size 1.000000
    s2 avalue font 0
    s2 avalue color 1
    s2 avalue rot 0
    s2 avalue format general
    s2 avalue prec 3
    s2 avalue prepend ""
    s2 avalue append ""
    s2 avalue offset 0.000000 , 0.000000
    s2 errorbar on
    s2 errorbar place both
    s2 errorbar color 11
    s2 errorbar pattern 1
    s2 errorbar size 1.000000
    s2 errorbar linewidth 1.0
    s2 errorbar linestyle 1
    s2 errorbar riser linewidth 1.0
    s2 errorbar riser linestyle 1
    s2 errorbar riser clip off
    s2 errorbar riser clip length 0.100000
    s2 comment "c2281/mtper.mfr"
    s2 legend  ""
    s3 hidden false
    s3 type xy
    s3 symbol 0
    s3 symbol size 1.000000
    s3 symbol color 11
    s3 symbol pattern 1
    s3 symbol fill color 11
    s3 symbol fill pattern 0
    s3 symbol linewidth 1.0
    s3 symbol linestyle 1
    s3 symbol char 65
    s3 symbol char font 0
    s3 symbol skip 0
    s3 line type 1
    s3 line linestyle 1
    s3 line linewidth 1.5
    s3 line color 11
    s3 line pattern 1
    s3 baseline type 0
    s3 baseline off
    s3 dropline off
    s3 fill type 0
    s3 fill rule 0
    s3 fill color 1
    s3 fill pattern 1
    s3 avalue off
    s3 avalue type 2
    s3 avalue char size 1.000000
    s3 avalue font 0
    s3 avalue color 1
    s3 avalue rot 0
    s3 avalue format general
    s3 avalue prec 3
    s3 avalue prepend ""
    s3 avalue append ""
    s3 avalue offset 0.000000 , 0.000000
    s3 errorbar on
    s3 errorbar place both
    s3 errorbar color 11
    s3 errorbar pattern 1
    s3 errorbar size 1.000000
    s3 errorbar linewidth 1.0
    s3 errorbar linestyle 1
    s3 errorbar riser linewidth 1.0
    s3 errorbar riser linestyle 1
    s3 errorbar riser clip off
    s3 errorbar riser clip length 0.100000
    s3 comment "c2281/mtper.mfr"
    s3 legend  ""
    s4 hidden false
    s4 type xy
    s4 symbol 0
    s4 symbol size 1.000000
    s4 symbol color 10
    s4 symbol pattern 1
    s4 symbol fill color 10
    s4 symbol fill pattern 0
    s4 symbol linewidth 1.0
    s4 symbol linestyle 1
    s4 symbol char 65
    s4 symbol char font 0
    s4 symbol skip 0
    s4 line type 1
    s4 line linestyle 3
    s4 line linewidth 2.0
    s4 line color 10
    s4 line pattern 1
    s4 baseline type 0
    s4 baseline off
    s4 dropline off
    s4 fill type 0
    s4 fill rule 0
    s4 fill color 1
    s4 fill pattern 1
    s4 avalue off
    s4 avalue type 2
    s4 avalue char size 1.000000
    s4 avalue font 0
    s4 avalue color 1
    s4 avalue rot 0
    s4 avalue format general
    s4 avalue prec 3
    s4 avalue prepend ""
    s4 avalue append ""
    s4 avalue offset 0.000000 , 0.000000
    s4 errorbar on
    s4 errorbar place both
    s4 errorbar color 10
    s4 errorbar pattern 1
    s4 errorbar size 1.000000
    s4 errorbar linewidth 1.0
    s4 errorbar linestyle 1
    s4 errorbar riser linewidth 1.0
    s4 errorbar riser linestyle 1
    s4 errorbar riser clip off
    s4 errorbar riser clip length 0.100000
    s4 comment "../../rate_ode/tv.mfr.a3"
    s4 legend  ""
    s5 hidden false
    s5 type xy
    s5 symbol 0
    s5 symbol size 1.000000
    s5 symbol color 10
    s5 symbol pattern 1
    s5 symbol fill color 10
    s5 symbol fill pattern 0
    s5 symbol linewidth 1.0
    s5 symbol linestyle 1
    s5 symbol char 65
    s5 symbol char font 0
    s5 symbol skip 0
    s5 line type 1
    s5 line linestyle 3
    s5 line linewidth 2.0
    s5 line color 10
    s5 line pattern 1
    s5 baseline type 0
    s5 baseline off
    s5 dropline off
    s5 fill type 0
    s5 fill rule 0
    s5 fill color 1
    s5 fill pattern 1
    s5 avalue off
    s5 avalue type 2
    s5 avalue char size 1.000000
    s5 avalue font 0
    s5 avalue color 1
    s5 avalue rot 0
    s5 avalue format general
    s5 avalue prec 3
    s5 avalue prepend ""
    s5 avalue append ""
    s5 avalue offset 0.000000 , 0.000000
    s5 errorbar on
    s5 errorbar place both
    s5 errorbar color 10
    s5 errorbar pattern 1
    s5 errorbar size 1.000000
    s5 errorbar linewidth 1.0
    s5 errorbar linestyle 1
    s5 errorbar riser linewidth 1.0
    s5 errorbar riser linestyle 1
    s5 errorbar riser clip off
    s5 errorbar riser clip length 0.100000
    s5 comment "../../rate_ode/tv.mfr.a3"
    s5 legend  ""
g3 on
g3 hidden false
g3 type XY
g3 stacked false
g3 bar hgap 0.000000
g3 fixedpoint off
g3 fixedpoint type 0
g3 fixedpoint xy 0.000000, 0.000000
g3 fixedpoint format general general
g3 fixedpoint prec 6, 6
with g3
    world 0, 0, 0.84, 14
    stack world 0, 0, 0, 0
    znorm 1
    view 0.150000, 0.320000, 0.400000, 0.480000
    title ""
    title font 0
    title size 1.500000
    title color 1
    subtitle ""
    subtitle font 0
    subtitle size 1.000000
    subtitle color 1
    xaxes scale Normal
    yaxes scale Normal
    xaxes invert off
    yaxes invert off
    xaxis  on
    xaxis  type zero false
    xaxis  offset 0.000000 , 0.000000
    xaxis  bar on
    xaxis  bar color 1
    xaxis  bar linestyle 1
    xaxis  bar linewidth 1.0
    xaxis  label ""
    xaxis  label layout para
    xaxis  label place auto
    xaxis  label char size 1.000000
    xaxis  label font 4
    xaxis  label color 1
    xaxis  label place normal
    xaxis  tick on
    xaxis  tick major 10
    xaxis  tick minor ticks 4
    xaxis  tick default 6
    xaxis  tick place rounded true
    xaxis  tick out
    xaxis  tick major size 0.460000
    xaxis  tick major color 1
    xaxis  tick major linewidth 1.0
    xaxis  tick major linestyle 1
    xaxis  tick major grid off
    xaxis  tick minor color 1
    xaxis  tick minor linewidth 1.0
    xaxis  tick minor linestyle 1
    xaxis  tick minor grid off
    xaxis  tick minor size 0.200000
    xaxis  ticklabel on
    xaxis  ticklabel format general
    xaxis  ticklabel prec 5
    xaxis  ticklabel formula ""
    xaxis  ticklabel append ""
    xaxis  ticklabel prepend ""
    xaxis  ticklabel angle 0
    xaxis  ticklabel skip 0
    xaxis  ticklabel stagger 0
    xaxis  ticklabel place normal
    xaxis  ticklabel offset auto
    xaxis  ticklabel offset 0.000000 , 0.010000
    xaxis  ticklabel start type spec
    xaxis  ticklabel start 2000.000000
    xaxis  ticklabel stop type auto
    xaxis  ticklabel stop 0.000000
    xaxis  ticklabel char size 1.000000
    xaxis  ticklabel font 4
    xaxis  ticklabel color 1
    xaxis  tick place normal
    xaxis  tick spec type none
    yaxis  on
    yaxis  type zero false
    yaxis  offset 0.000000 , 0.000000
    yaxis  bar on
    yaxis  bar color 1
    yaxis  bar linestyle 1
    yaxis  bar linewidth 1.0
    yaxis  label " Frequency,\n\v{-0.3}1/T\svIRt\N\v{-0.2} (Hz)"
    yaxis  label layout para
    yaxis  label place auto
    yaxis  label char size 0.800000
    yaxis  label font 4
    yaxis  label color 1
    yaxis  label place normal
    yaxis  tick on
    yaxis  tick major 5
    yaxis  tick minor ticks 4
    yaxis  tick default 6
    yaxis  tick place rounded true
    yaxis  tick out
    yaxis  tick major size 0.460000
    yaxis  tick major color 1
    yaxis  tick major linewidth 1.0
    yaxis  tick major linestyle 1
    yaxis  tick major grid off
    yaxis  tick minor color 1
    yaxis  tick minor linewidth 1.0
    yaxis  tick minor linestyle 1
    yaxis  tick minor grid off
    yaxis  tick minor size 0.200000
    yaxis  ticklabel on
    yaxis  ticklabel format general
    yaxis  ticklabel prec 5
    yaxis  ticklabel formula ""
    yaxis  ticklabel append ""
    yaxis  ticklabel prepend ""
    yaxis  ticklabel angle 0
    yaxis  ticklabel skip 0
    yaxis  ticklabel stagger 0
    yaxis  ticklabel place normal
    yaxis  ticklabel offset auto
    yaxis  ticklabel offset 0.000000 , 0.010000
    yaxis  ticklabel start type auto
    yaxis  ticklabel start 0.000000
    yaxis  ticklabel stop type auto
    yaxis  ticklabel stop 0.000000
    yaxis  ticklabel char size 0.800000
    yaxis  ticklabel font 4
    yaxis  ticklabel color 1
    yaxis  tick place normal
    yaxis  tick spec type none
    altxaxis  off
    altyaxis  off
    legend on
    legend loctype view
    legend 0.69, 0.9
    legend box color 1
    legend box pattern 1
    legend box linewidth 1.0
    legend box linestyle 1
    legend box fill color 0
    legend box fill pattern 1
    legend font 0
    legend char size 1.000000
    legend color 1
    legend length 4
    legend vgap 1
    legend hgap 1
    legend invert false
    frame type 1
    frame linestyle 1
    frame linewidth 1.0
    frame color 1
    frame pattern 1
    frame background color 0
    frame background pattern 0
    s0 hidden false
    s0 type xydy
    s0 symbol 1
    s0 symbol size 0.210000
    s0 symbol color 1
    s0 symbol pattern 1
    s0 symbol fill color 1
    s0 symbol fill pattern 1
    s0 symbol linewidth 1.0
    s0 symbol linestyle 1
    s0 symbol char 65
    s0 symbol char font 0
    s0 symbol skip 0
    s0 line type 0
    s0 line linestyle 1
    s0 line linewidth 1.0
    s0 line color 1
    s0 line pattern 1
    s0 baseline type 0
    s0 baseline off
    s0 dropline off
    s0 fill type 0
    s0 fill rule 0
    s0 fill color 1
    s0 fill pattern 1
    s0 avalue off
    s0 avalue type 2
    s0 avalue char size 1.000000
    s0 avalue font 0
    s0 avalue color 1
    s0 avalue rot 0
    s0 avalue format general
    s0 avalue prec 3
    s0 avalue prepend ""
    s0 avalue append ""
    s0 avalue offset 0.000000 , 0.000000
    s0 errorbar on
    s0 errorbar place both
    s0 errorbar color 1
    s0 errorbar pattern 1
    s0 errorbar size 0.170000
    s0 errorbar linewidth 1.0
    s0 errorbar linestyle 1
    s0 errorbar riser linewidth 1.0
    s0 errorbar riser linestyle 1
    s0 errorbar riser clip off
    s0 errorbar riser clip length 0.100000
    s0 comment "c227/tperst.col"
    s0 legend  ""
    s1 hidden false
    s1 type xy
    s1 symbol 0
    s1 symbol size 1.000000
    s1 symbol color 11
    s1 symbol pattern 1
    s1 symbol fill color 11
    s1 symbol fill pattern 0
    s1 symbol linewidth 1.0
    s1 symbol linestyle 1
    s1 symbol char 65
    s1 symbol char font 0
    s1 symbol skip 0
    s1 line type 1
    s1 line linestyle 1
    s1 line linewidth 1.5
    s1 line color 11
    s1 line pattern 1
    s1 baseline type 0
    s1 baseline off
    s1 dropline off
    s1 fill type 0
    s1 fill rule 0
    s1 fill color 1
    s1 fill pattern 1
    s1 avalue off
    s1 avalue type 2
    s1 avalue char size 1.000000
    s1 avalue font 0
    s1 avalue color 1
    s1 avalue rot 0
    s1 avalue format general
    s1 avalue prec 3
    s1 avalue prepend ""
    s1 avalue append ""
    s1 avalue offset 0.000000 , 0.000000
    s1 errorbar on
    s1 errorbar place both
    s1 errorbar color 11
    s1 errorbar pattern 1
    s1 errorbar size 1.000000
    s1 errorbar linewidth 1.0
    s1 errorbar linestyle 1
    s1 errorbar riser linewidth 1.0
    s1 errorbar riser linestyle 1
    s1 errorbar riser clip off
    s1 errorbar riser clip length 0.100000
    s1 comment "c227/tperst.col"
    s1 legend  ""
    s2 hidden false
    s2 type xy
    s2 symbol 0
    s2 symbol size 1.000000
    s2 symbol color 10
    s2 symbol pattern 1
    s2 symbol fill color 10
    s2 symbol fill pattern 0
    s2 symbol linewidth 1.0
    s2 symbol linestyle 1
    s2 symbol char 65
    s2 symbol char font 0
    s2 symbol skip 0
    s2 line type 1
    s2 line linestyle 3
    s2 line linewidth 2.0
    s2 line color 10
    s2 line pattern 1
    s2 baseline type 0
    s2 baseline off
    s2 dropline off
    s2 fill type 0
    s2 fill rule 0
    s2 fill color 1
    s2 fill pattern 1
    s2 avalue off
    s2 avalue type 2
    s2 avalue char size 1.000000
    s2 avalue font 0
    s2 avalue color 1
    s2 avalue rot 0
    s2 avalue format general
    s2 avalue prec 3
    s2 avalue prepend ""
    s2 avalue append ""
    s2 avalue offset 0.000000 , 0.000000
    s2 errorbar on
    s2 errorbar place both
    s2 errorbar color 10
    s2 errorbar pattern 1
    s2 errorbar size 1.000000
    s2 errorbar linewidth 1.0
    s2 errorbar linestyle 1
    s2 errorbar riser linewidth 1.0
    s2 errorbar riser linestyle 1
    s2 errorbar riser clip off
    s2 errorbar riser clip length 0.100000
    s2 comment "c227/tperst.col"
    s2 legend  ""
g4 on
g4 hidden false
g4 type XY
g4 stacked false
g4 bar hgap 0.000000
g4 fixedpoint off
g4 fixedpoint type 0
g4 fixedpoint xy 0.000000, 0.000000
g4 fixedpoint format general general
g4 fixedpoint prec 6, 6
with g4
    world 0, -0.2, 0.84, 30
    stack world 0, 0, 0, 0
    znorm 1
    view 0.150000, 0.550000, 0.400000, 0.740000
    title ""
    title font 0
    title size 1.500000
    title color 1
    subtitle ""
    subtitle font 0
    subtitle size 1.000000
    subtitle color 1
    xaxes scale Normal
    yaxes scale Normal
    xaxes invert off
    yaxes invert off
    xaxis  on
    xaxis  type zero false
    xaxis  offset 0.000000 , 0.000000
    xaxis  bar on
    xaxis  bar color 1
    xaxis  bar linestyle 1
    xaxis  bar linewidth 1.0
    xaxis  label ""
    xaxis  label layout para
    xaxis  label place auto
    xaxis  label char size 1.000000
    xaxis  label font 4
    xaxis  label color 1
    xaxis  label place normal
    xaxis  tick on
    xaxis  tick major 10
    xaxis  tick minor ticks 4
    xaxis  tick default 6
    xaxis  tick place rounded true
    xaxis  tick out
    xaxis  tick major size 0.460000
    xaxis  tick major color 1
    xaxis  tick major linewidth 1.0
    xaxis  tick major linestyle 1
    xaxis  tick major grid off
    xaxis  tick minor color 1
    xaxis  tick minor linewidth 1.0
    xaxis  tick minor linestyle 1
    xaxis  tick minor grid off
    xaxis  tick minor size 0.200000
    xaxis  ticklabel on
    xaxis  ticklabel format general
    xaxis  ticklabel prec 5
    xaxis  ticklabel formula ""
    xaxis  ticklabel append ""
    xaxis  ticklabel prepend ""
    xaxis  ticklabel angle 0
    xaxis  ticklabel skip 0
    xaxis  ticklabel stagger 0
    xaxis  ticklabel place normal
    xaxis  ticklabel offset auto
    xaxis  ticklabel offset 0.000000 , 0.010000
    xaxis  ticklabel start type spec
    xaxis  ticklabel start 2000.000000
    xaxis  ticklabel stop type auto
    xaxis  ticklabel stop 0.000000
    xaxis  ticklabel char size 1.000000
    xaxis  ticklabel font 4
    xaxis  ticklabel color 1
    xaxis  tick place normal
    xaxis  tick spec type none
    yaxis  on
    yaxis  type zero false
    yaxis  offset 0.000000 , 0.000000
    yaxis  bar on
    yaxis  bar color 1
    yaxis  bar linestyle 1
    yaxis  bar linewidth 1.0
    yaxis  label "Whisking\N amplitude,\n\v{-0.3}         <\f{Symbol}q\f{Helvetica}\Samp\N\v{-0.2}>\st\N"
    yaxis  label layout para
    yaxis  label place spec
    yaxis  label place 0.000000, 0.083000
    yaxis  label char size 0.800000
    yaxis  label font 4
    yaxis  label color 1
    yaxis  label place normal
    yaxis  tick on
    yaxis  tick major 15
    yaxis  tick minor ticks 2
    yaxis  tick default 6
    yaxis  tick place rounded true
    yaxis  tick out
    yaxis  tick major size 0.460000
    yaxis  tick major color 1
    yaxis  tick major linewidth 1.0
    yaxis  tick major linestyle 1
    yaxis  tick major grid off
    yaxis  tick minor color 1
    yaxis  tick minor linewidth 1.0
    yaxis  tick minor linestyle 1
    yaxis  tick minor grid off
    yaxis  tick minor size 0.200000
    yaxis  ticklabel on
    yaxis  ticklabel format general
    yaxis  ticklabel prec 5
    yaxis  ticklabel formula ""
    yaxis  ticklabel append ""
    yaxis  ticklabel prepend ""
    yaxis  ticklabel angle 0
    yaxis  ticklabel skip 0
    yaxis  ticklabel stagger 0
    yaxis  ticklabel place normal
    yaxis  ticklabel offset auto
    yaxis  ticklabel offset 0.000000 , 0.010000
    yaxis  ticklabel start type auto
    yaxis  ticklabel start 0.000000
    yaxis  ticklabel stop type auto
    yaxis  ticklabel stop 0.000000
    yaxis  ticklabel char size 0.800000
    yaxis  ticklabel font 4
    yaxis  ticklabel color 1
    yaxis  tick place normal
    yaxis  tick spec type both
    yaxis  tick spec 7
    yaxis  tick major 0, 0
    yaxis  ticklabel 0, "0\h{-0.035}°"
    yaxis  tick minor 1, 5
    yaxis  tick minor 2, 10
    yaxis  tick major 3, 15
    yaxis  ticklabel 3, "15\h{-0.05}°"
    yaxis  tick minor 4, 20
    yaxis  tick minor 5, 25
    yaxis  tick major 6, 30
    yaxis  ticklabel 6, "30\h{-0.05}°"
    altxaxis  off
    altyaxis  off
    legend on
    legend loctype view
    legend 0.69, 0.3
    legend box color 1
    legend box pattern 0
    legend box linewidth 1.0
    legend box linestyle 0
    legend box fill color 0
    legend box fill pattern 1
    legend font 4
    legend char size 0.780000
    legend color 1
    legend length 3
    legend vgap 1
    legend hgap 1
    legend invert false
    frame type 1
    frame linestyle 1
    frame linewidth 1.0
    frame color 1
    frame pattern 1
    frame background color 0
    frame background pattern 0
    s0 hidden false
    s0 type xydy
    s0 symbol 0
    s0 symbol size 0.210000
    s0 symbol color 1
    s0 symbol pattern 1
    s0 symbol fill color 1
    s0 symbol fill pattern 1
    s0 symbol linewidth 1.0
    s0 symbol linestyle 1
    s0 symbol char 65
    s0 symbol char font 0
    s0 symbol skip 0
    s0 line type 0
    s0 line linestyle 1
    s0 line linewidth 1.0
    s0 line color 1
    s0 line pattern 1
    s0 baseline type 0
    s0 baseline off
    s0 dropline off
    s0 fill type 0
    s0 fill rule 0
    s0 fill color 1
    s0 fill pattern 1
    s0 avalue off
    s0 avalue type 2
    s0 avalue char size 1.000000
    s0 avalue font 0
    s0 avalue color 1
    s0 avalue rot 0
    s0 avalue format general
    s0 avalue prec 3
    s0 avalue prepend ""
    s0 avalue append ""
    s0 avalue offset 0.000000 , 0.000000
    s0 errorbar on
    s0 errorbar place both
    s0 errorbar color 1
    s0 errorbar pattern 1
    s0 errorbar size 0.170000
    s0 errorbar linewidth 1.0
    s0 errorbar linestyle 0
    s0 errorbar riser linewidth 1.0
    s0 errorbar riser linestyle 0
    s0 errorbar riser clip off
    s0 errorbar riser clip length 0.100000
    s0 comment "c227/tperst.col"
    s0 legend  ""
    s1 hidden false
    s1 type xydy
    s1 symbol 0
    s1 symbol size 0.210000
    s1 symbol color 7
    s1 symbol pattern 1
    s1 symbol fill color 7
    s1 symbol fill pattern 1
    s1 symbol linewidth 1.0
    s1 symbol linestyle 1
    s1 symbol char 65
    s1 symbol char font 0
    s1 symbol skip 0
    s1 line type 0
    s1 line linestyle 1
    s1 line linewidth 1.0
    s1 line color 7
    s1 line pattern 1
    s1 baseline type 0
    s1 baseline off
    s1 dropline off
    s1 fill type 0
    s1 fill rule 0
    s1 fill color 1
    s1 fill pattern 1
    s1 avalue off
    s1 avalue type 2
    s1 avalue char size 1.000000
    s1 avalue font 0
    s1 avalue color 1
    s1 avalue rot 0
    s1 avalue format general
    s1 avalue prec 3
    s1 avalue prepend ""
    s1 avalue append ""
    s1 avalue offset 0.000000 , 0.000000
    s1 errorbar on
    s1 errorbar place both
    s1 errorbar color 7
    s1 errorbar pattern 1
    s1 errorbar size 0.170000
    s1 errorbar linewidth 1.0
    s1 errorbar linestyle 0
    s1 errorbar riser linewidth 1.0
    s1 errorbar riser linestyle 0
    s1 errorbar riser clip off
    s1 errorbar riser clip length 0.100000
    s1 comment "c2281/mtper.mfr"
    s1 legend  ""
    s2 hidden false
    s2 type xydy
    s2 symbol 1
    s2 symbol size 0.210000
    s2 symbol color 1
    s2 symbol pattern 1
    s2 symbol fill color 1
    s2 symbol fill pattern 1
    s2 symbol linewidth 1.0
    s2 symbol linestyle 1
    s2 symbol char 65
    s2 symbol char font 0
    s2 symbol skip 0
    s2 line type 0
    s2 line linestyle 0
    s2 line linewidth 1.0
    s2 line color 3
    s2 line pattern 1
    s2 baseline type 0
    s2 baseline off
    s2 dropline off
    s2 fill type 0
    s2 fill rule 0
    s2 fill color 1
    s2 fill pattern 1
    s2 avalue off
    s2 avalue type 2
    s2 avalue char size 1.000000
    s2 avalue font 0
    s2 avalue color 1
    s2 avalue rot 0
    s2 avalue format general
    s2 avalue prec 3
    s2 avalue prepend ""
    s2 avalue append ""
    s2 avalue offset 0.000000 , 0.000000
    s2 errorbar on
    s2 errorbar place both
    s2 errorbar color 1
    s2 errorbar pattern 1
    s2 errorbar size 0.180000
    s2 errorbar linewidth 1.0
    s2 errorbar linestyle 1
    s2 errorbar riser linewidth 1.0
    s2 errorbar riser linestyle 1
    s2 errorbar riser clip off
    s2 errorbar riser clip length 0.100000
    s2 comment "dat_qsub/no_pb_x_ginter_intra/cmt.wsk"
    s2 legend  ""
    s3 hidden false
    s3 type xydy
    s3 symbol 1
    s3 symbol size 0.210000
    s3 symbol color 7
    s3 symbol pattern 1
    s3 symbol fill color 7
    s3 symbol fill pattern 0
    s3 symbol linewidth 1.0
    s3 symbol linestyle 1
    s3 symbol char 65
    s3 symbol char font 0
    s3 symbol skip 0
    s3 line type 0
    s3 line linestyle 1
    s3 line linewidth 1.0
    s3 line color 15
    s3 line pattern 1
    s3 baseline type 0
    s3 baseline off
    s3 dropline off
    s3 fill type 0
    s3 fill rule 0
    s3 fill color 1
    s3 fill pattern 1
    s3 avalue off
    s3 avalue type 2
    s3 avalue char size 1.000000
    s3 avalue font 0
    s3 avalue color 1
    s3 avalue rot 0
    s3 avalue format general
    s3 avalue prec 3
    s3 avalue prepend ""
    s3 avalue append ""
    s3 avalue offset 0.000000 , 0.000000
    s3 errorbar on
    s3 errorbar place both
    s3 errorbar color 7
    s3 errorbar pattern 1
    s3 errorbar size 0.180000
    s3 errorbar linewidth 1.0
    s3 errorbar linestyle 1
    s3 errorbar riser linewidth 1.0
    s3 errorbar riser linestyle 1
    s3 errorbar riser clip off
    s3 errorbar riser clip length 0.100000
    s3 comment "dat_qsub/no_pb_x_ginter_intra/cmt.wsk"
    s3 legend  ""
    s4 hidden false
    s4 type xy
    s4 symbol 0
    s4 symbol size 1.000000
    s4 symbol color 11
    s4 symbol pattern 1
    s4 symbol fill color 11
    s4 symbol fill pattern 0
    s4 symbol linewidth 1.0
    s4 symbol linestyle 1
    s4 symbol char 65
    s4 symbol char font 0
    s4 symbol skip 0
    s4 line type 1
    s4 line linestyle 1
    s4 line linewidth 1.5
    s4 line color 11
    s4 line pattern 1
    s4 baseline type 0
    s4 baseline off
    s4 dropline off
    s4 fill type 0
    s4 fill rule 0
    s4 fill color 1
    s4 fill pattern 1
    s4 avalue off
    s4 avalue type 2
    s4 avalue char size 1.000000
    s4 avalue font 0
    s4 avalue color 1
    s4 avalue rot 0
    s4 avalue format general
    s4 avalue prec 3
    s4 avalue prepend ""
    s4 avalue append ""
    s4 avalue offset 0.000000 , 0.000000
    s4 errorbar on
    s4 errorbar place both
    s4 errorbar color 11
    s4 errorbar pattern 1
    s4 errorbar size 1.000000
    s4 errorbar linewidth 1.0
    s4 errorbar linestyle 1
    s4 errorbar riser linewidth 1.0
    s4 errorbar riser linestyle 1
    s4 errorbar riser clip off
    s4 errorbar riser clip length 0.100000
    s4 comment "dat_qsub/no_pb_x_ginter_no_intra/cmt.wsk_amp_ct"
    s4 legend  ""
    s5 hidden false
    s5 type xy
    s5 symbol 0
    s5 symbol size 1.000000
    s5 symbol color 10
    s5 symbol pattern 1
    s5 symbol fill color 10
    s5 symbol fill pattern 0
    s5 symbol linewidth 1.0
    s5 symbol linestyle 1
    s5 symbol char 65
    s5 symbol char font 0
    s5 symbol skip 0
    s5 line type 1
    s5 line linestyle 3
    s5 line linewidth 2.0
    s5 line color 10
    s5 line pattern 1
    s5 baseline type 0
    s5 baseline off
    s5 dropline off
    s5 fill type 0
    s5 fill rule 0
    s5 fill color 1
    s5 fill pattern 1
    s5 avalue off
    s5 avalue type 2
    s5 avalue char size 1.000000
    s5 avalue font 0
    s5 avalue color 1
    s5 avalue rot 0
    s5 avalue format general
    s5 avalue prec 3
    s5 avalue prepend ""
    s5 avalue append ""
    s5 avalue offset 0.000000 , 0.000000
    s5 errorbar on
    s5 errorbar place both
    s5 errorbar color 10
    s5 errorbar pattern 1
    s5 errorbar size 1.000000
    s5 errorbar linewidth 1.0
    s5 errorbar linestyle 1
    s5 errorbar riser linewidth 1.0
    s5 errorbar riser linestyle 1
    s5 errorbar riser clip off
    s5 errorbar riser clip length 0.100000
    s5 comment "../../rate_num/datfig/no_pb_x_ginter_no_intra/tvnc.amp"
    s5 legend  ""
    s6 hidden false
    s6 type xy
    s6 symbol 0
    s6 symbol size 1.000000
    s6 symbol color 10
    s6 symbol pattern 1
    s6 symbol fill color 10
    s6 symbol fill pattern 0
    s6 symbol linewidth 1.0
    s6 symbol linestyle 1
    s6 symbol char 65
    s6 symbol char font 0
    s6 symbol skip 0
    s6 line type 1
    s6 line linestyle 3
    s6 line linewidth 2.0
    s6 line color 10
    s6 line pattern 1
    s6 baseline type 0
    s6 baseline off
    s6 dropline off
    s6 fill type 0
    s6 fill rule 0
    s6 fill color 1
    s6 fill pattern 1
    s6 avalue off
    s6 avalue type 2
    s6 avalue char size 1.000000
    s6 avalue font 0
    s6 avalue color 1
    s6 avalue rot 0
    s6 avalue format general
    s6 avalue prec 3
    s6 avalue prepend ""
    s6 avalue append ""
    s6 avalue offset 0.000000 , 0.000000
    s6 errorbar on
    s6 errorbar place both
    s6 errorbar color 10
    s6 errorbar pattern 1
    s6 errorbar size 1.000000
    s6 errorbar linewidth 1.0
    s6 errorbar linestyle 1
    s6 errorbar riser linewidth 1.0
    s6 errorbar riser linestyle 1
    s6 errorbar riser clip off
    s6 errorbar riser clip length 0.100000
    s6 comment "../../rate_num/datfig/no_pb_x_ginter_no_intra/tvnc.amp"
    s6 legend  ""
g5 on
g5 hidden false
g5 type XY
g5 stacked false
g5 bar hgap 0.000000
g5 fixedpoint off
g5 fixedpoint type 0
g5 fixedpoint xy 0.000000, 0.000000
g5 fixedpoint format general general
g5 fixedpoint prec 6, 6
with g5
    world 0, -0.4, 0.84, 60
    stack world 0, 0, 0, 0
    znorm 1
    view 0.150000, 0.090000, 0.400000, 0.250000
    title ""
    title font 0
    title size 1.500000
    title color 1
    subtitle ""
    subtitle font 0
    subtitle size 1.000000
    subtitle color 1
    xaxes scale Normal
    yaxes scale Normal
    xaxes invert off
    yaxes invert off
    xaxis  on
    xaxis  type zero false
    xaxis  offset 0.000000 , 0.000000
    xaxis  bar on
    xaxis  bar color 1
    xaxis  bar linestyle 1
    xaxis  bar linewidth 1.0
    xaxis  label ""
    xaxis  label layout para
    xaxis  label place auto
    xaxis  label char size 1.000000
    xaxis  label font 4
    xaxis  label color 1
    xaxis  label place normal
    xaxis  tick on
    xaxis  tick major 10
    xaxis  tick minor ticks 4
    xaxis  tick default 6
    xaxis  tick place rounded true
    xaxis  tick out
    xaxis  tick major size 0.460000
    xaxis  tick major color 1
    xaxis  tick major linewidth 1.0
    xaxis  tick major linestyle 1
    xaxis  tick major grid off
    xaxis  tick minor color 1
    xaxis  tick minor linewidth 1.0
    xaxis  tick minor linestyle 1
    xaxis  tick minor grid off
    xaxis  tick minor size 0.200000
    xaxis  ticklabel on
    xaxis  ticklabel format general
    xaxis  ticklabel prec 5
    xaxis  ticklabel formula ""
    xaxis  ticklabel append ""
    xaxis  ticklabel prepend ""
    xaxis  ticklabel angle 0
    xaxis  ticklabel skip 0
    xaxis  ticklabel stagger 0
    xaxis  ticklabel place normal
    xaxis  ticklabel offset auto
    xaxis  ticklabel offset 0.000000 , 0.010000
    xaxis  ticklabel start type spec
    xaxis  ticklabel start 2000.000000
    xaxis  ticklabel stop type auto
    xaxis  ticklabel stop 0.000000
    xaxis  ticklabel char size 1.000000
    xaxis  ticklabel font 4
    xaxis  ticklabel color 1
    xaxis  tick place normal
    xaxis  tick spec type none
    yaxis  on
    yaxis  type zero false
    yaxis  offset 0.000000 , 0.000000
    yaxis  bar on
    yaxis  bar color 1
    yaxis  bar linestyle 1
    yaxis  bar linewidth 1.0
    yaxis  label "Vibrissa set-point,\n\v{-0.3}         <\f{Symbol}q\f{Helvetica}\Sset\N\v{-0.2}>\st\N"
    yaxis  label layout para
    yaxis  label place spec
    yaxis  label place 0.000000, 0.083000
    yaxis  label char size 0.800000
    yaxis  label font 4
    yaxis  label color 1
    yaxis  label place normal
    yaxis  tick on
    yaxis  tick major 20
    yaxis  tick minor ticks 3
    yaxis  tick default 6
    yaxis  tick place rounded true
    yaxis  tick out
    yaxis  tick major size 0.460000
    yaxis  tick major color 1
    yaxis  tick major linewidth 1.0
    yaxis  tick major linestyle 1
    yaxis  tick major grid off
    yaxis  tick minor color 1
    yaxis  tick minor linewidth 1.0
    yaxis  tick minor linestyle 1
    yaxis  tick minor grid off
    yaxis  tick minor size 0.200000
    yaxis  ticklabel on
    yaxis  ticklabel format general
    yaxis  ticklabel prec 5
    yaxis  ticklabel formula ""
    yaxis  ticklabel append ""
    yaxis  ticklabel prepend ""
    yaxis  ticklabel angle 0
    yaxis  ticklabel skip 0
    yaxis  ticklabel stagger 0
    yaxis  ticklabel place normal
    yaxis  ticklabel offset auto
    yaxis  ticklabel offset 0.000000 , 0.010000
    yaxis  ticklabel start type auto
    yaxis  ticklabel start 0.000000
    yaxis  ticklabel stop type auto
    yaxis  ticklabel stop 0.000000
    yaxis  ticklabel char size 0.800000
    yaxis  ticklabel font 4
    yaxis  ticklabel color 1
    yaxis  tick place normal
    yaxis  tick spec type both
    yaxis  tick spec 13
    yaxis  tick major 0, 0
    yaxis  ticklabel 0, "0\h{-0.035}°"
    yaxis  tick minor 1, 5
    yaxis  tick minor 2, 10
    yaxis  tick minor 3, 15
    yaxis  tick major 4, 20
    yaxis  ticklabel 4, "20\h{-0.05}°"
    yaxis  tick minor 5, 25
    yaxis  tick minor 6, 30
    yaxis  tick minor 7, 35
    yaxis  tick major 8, 40
    yaxis  ticklabel 8, "40\h{-0.05}°"
    yaxis  tick minor 9, 45
    yaxis  tick minor 10, 50
    yaxis  tick minor 11, 55
    yaxis  tick major 12, 60
    yaxis  ticklabel 12, "60\h{-0.05}°"
    altxaxis  off
    altyaxis  off
    legend on
    legend loctype view
    legend 0.69, 0.3
    legend box color 1
    legend box pattern 0
    legend box linewidth 1.0
    legend box linestyle 0
    legend box fill color 0
    legend box fill pattern 1
    legend font 4
    legend char size 0.780000
    legend color 1
    legend length 3
    legend vgap 1
    legend hgap 1
    legend invert false
    frame type 1
    frame linestyle 1
    frame linewidth 1.0
    frame color 1
    frame pattern 1
    frame background color 0
    frame background pattern 0
    s0 hidden false
    s0 type xydy
    s0 symbol 1
    s0 symbol size 0.210000
    s0 symbol color 1
    s0 symbol pattern 1
    s0 symbol fill color 1
    s0 symbol fill pattern 1
    s0 symbol linewidth 1.0
    s0 symbol linestyle 1
    s0 symbol char 65
    s0 symbol char font 0
    s0 symbol skip 0
    s0 line type 0
    s0 line linestyle 1
    s0 line linewidth 1.0
    s0 line color 1
    s0 line pattern 1
    s0 baseline type 0
    s0 baseline off
    s0 dropline off
    s0 fill type 0
    s0 fill rule 0
    s0 fill color 1
    s0 fill pattern 1
    s0 avalue off
    s0 avalue type 2
    s0 avalue char size 1.000000
    s0 avalue font 0
    s0 avalue color 1
    s0 avalue rot 0
    s0 avalue format general
    s0 avalue prec 3
    s0 avalue prepend ""
    s0 avalue append ""
    s0 avalue offset 0.000000 , 0.000000
    s0 errorbar on
    s0 errorbar place both
    s0 errorbar color 1
    s0 errorbar pattern 1
    s0 errorbar size 0.170000
    s0 errorbar linewidth 1.0
    s0 errorbar linestyle 1
    s0 errorbar riser linewidth 1.0
    s0 errorbar riser linestyle 1
    s0 errorbar riser clip off
    s0 errorbar riser clip length 0.100000
    s0 comment "c227/tperst.col"
    s0 legend  ""
    s1 hidden false
    s1 type xydy
    s1 symbol 1
    s1 symbol size 0.210000
    s1 symbol color 7
    s1 symbol pattern 1
    s1 symbol fill color 7
    s1 symbol fill pattern 1
    s1 symbol linewidth 1.0
    s1 symbol linestyle 1
    s1 symbol char 65
    s1 symbol char font 0
    s1 symbol skip 0
    s1 line type 0
    s1 line linestyle 1
    s1 line linewidth 1.0
    s1 line color 7
    s1 line pattern 1
    s1 baseline type 0
    s1 baseline off
    s1 dropline off
    s1 fill type 0
    s1 fill rule 0
    s1 fill color 1
    s1 fill pattern 1
    s1 avalue off
    s1 avalue type 2
    s1 avalue char size 1.000000
    s1 avalue font 0
    s1 avalue color 1
    s1 avalue rot 0
    s1 avalue format general
    s1 avalue prec 3
    s1 avalue prepend ""
    s1 avalue append ""
    s1 avalue offset 0.000000 , 0.000000
    s1 errorbar on
    s1 errorbar place both
    s1 errorbar color 7
    s1 errorbar pattern 1
    s1 errorbar size 0.170000
    s1 errorbar linewidth 1.0
    s1 errorbar linestyle 1
    s1 errorbar riser linewidth 1.0
    s1 errorbar riser linestyle 1
    s1 errorbar riser clip off
    s1 errorbar riser clip length 0.100000
    s1 comment "c2281/mtper.mfr"
    s1 legend  ""
    s2 hidden false
    s2 type xydy
    s2 symbol 0
    s2 symbol size 0.210000
    s2 symbol color 1
    s2 symbol pattern 1
    s2 symbol fill color 1
    s2 symbol fill pattern 1
    s2 symbol linewidth 1.0
    s2 symbol linestyle 1
    s2 symbol char 65
    s2 symbol char font 0
    s2 symbol skip 0
    s2 line type 0
    s2 line linestyle 0
    s2 line linewidth 1.0
    s2 line color 3
    s2 line pattern 1
    s2 baseline type 0
    s2 baseline off
    s2 dropline off
    s2 fill type 0
    s2 fill rule 0
    s2 fill color 1
    s2 fill pattern 1
    s2 avalue off
    s2 avalue type 2
    s2 avalue char size 1.000000
    s2 avalue font 0
    s2 avalue color 1
    s2 avalue rot 0
    s2 avalue format general
    s2 avalue prec 3
    s2 avalue prepend ""
    s2 avalue append ""
    s2 avalue offset 0.000000 , 0.000000
    s2 errorbar on
    s2 errorbar place both
    s2 errorbar color 1
    s2 errorbar pattern 1
    s2 errorbar size 0.180000
    s2 errorbar linewidth 1.0
    s2 errorbar linestyle 0
    s2 errorbar riser linewidth 1.0
    s2 errorbar riser linestyle 0
    s2 errorbar riser clip off
    s2 errorbar riser clip length 0.100000
    s2 comment "dat_qsub/no_pb_x_ginter_intra/cmt.wsk"
    s2 legend  ""
    s3 hidden false
    s3 type xydy
    s3 symbol 0
    s3 symbol size 0.210000
    s3 symbol color 7
    s3 symbol pattern 1
    s3 symbol fill color 7
    s3 symbol fill pattern 0
    s3 symbol linewidth 1.0
    s3 symbol linestyle 1
    s3 symbol char 65
    s3 symbol char font 0
    s3 symbol skip 0
    s3 line type 0
    s3 line linestyle 1
    s3 line linewidth 1.0
    s3 line color 15
    s3 line pattern 1
    s3 baseline type 0
    s3 baseline off
    s3 dropline off
    s3 fill type 0
    s3 fill rule 0
    s3 fill color 1
    s3 fill pattern 1
    s3 avalue off
    s3 avalue type 2
    s3 avalue char size 1.000000
    s3 avalue font 0
    s3 avalue color 1
    s3 avalue rot 0
    s3 avalue format general
    s3 avalue prec 3
    s3 avalue prepend ""
    s3 avalue append ""
    s3 avalue offset 0.000000 , 0.000000
    s3 errorbar on
    s3 errorbar place both
    s3 errorbar color 7
    s3 errorbar pattern 1
    s3 errorbar size 0.180000
    s3 errorbar linewidth 1.0
    s3 errorbar linestyle 0
    s3 errorbar riser linewidth 1.0
    s3 errorbar riser linestyle 0
    s3 errorbar riser clip off
    s3 errorbar riser clip length 0.100000
    s3 comment "dat_qsub/no_pb_x_ginter_intra/cmt.wsk"
    s3 legend  ""
    s4 hidden false
    s4 type xy
    s4 symbol 0
    s4 symbol size 1.000000
    s4 symbol color 11
    s4 symbol pattern 1
    s4 symbol fill color 11
    s4 symbol fill pattern 0
    s4 symbol linewidth 1.0
    s4 symbol linestyle 1
    s4 symbol char 65
    s4 symbol char font 0
    s4 symbol skip 0
    s4 line type 1
    s4 line linestyle 1
    s4 line linewidth 1.5
    s4 line color 11
    s4 line pattern 1
    s4 baseline type 0
    s4 baseline off
    s4 dropline off
    s4 fill type 0
    s4 fill rule 0
    s4 fill color 1
    s4 fill pattern 1
    s4 avalue off
    s4 avalue type 2
    s4 avalue char size 1.000000
    s4 avalue font 0
    s4 avalue color 1
    s4 avalue rot 0
    s4 avalue format general
    s4 avalue prec 3
    s4 avalue prepend ""
    s4 avalue append ""
    s4 avalue offset 0.000000 , 0.000000
    s4 errorbar on
    s4 errorbar place both
    s4 errorbar color 11
    s4 errorbar pattern 1
    s4 errorbar size 1.000000
    s4 errorbar linewidth 1.0
    s4 errorbar linestyle 1
    s4 errorbar riser linewidth 1.0
    s4 errorbar riser linestyle 1
    s4 errorbar riser clip off
    s4 errorbar riser clip length 0.100000
    s4 comment "dat_qsub/no_pb_x_ginter_no_intra/cmt.wsk_amp_ct"
    s4 legend  ""
    s5 hidden false
    s5 type xy
    s5 symbol 0
    s5 symbol size 1.000000
    s5 symbol color 11
    s5 symbol pattern 1
    s5 symbol fill color 11
    s5 symbol fill pattern 0
    s5 symbol linewidth 1.0
    s5 symbol linestyle 1
    s5 symbol char 65
    s5 symbol char font 0
    s5 symbol skip 0
    s5 line type 1
    s5 line linestyle 1
    s5 line linewidth 1.5
    s5 line color 11
    s5 line pattern 1
    s5 baseline type 0
    s5 baseline off
    s5 dropline off
    s5 fill type 0
    s5 fill rule 0
    s5 fill color 1
    s5 fill pattern 1
    s5 avalue off
    s5 avalue type 2
    s5 avalue char size 1.000000
    s5 avalue font 0
    s5 avalue color 1
    s5 avalue rot 0
    s5 avalue format general
    s5 avalue prec 3
    s5 avalue prepend ""
    s5 avalue append ""
    s5 avalue offset 0.000000 , 0.000000
    s5 errorbar on
    s5 errorbar place both
    s5 errorbar color 11
    s5 errorbar pattern 1
    s5 errorbar size 1.000000
    s5 errorbar linewidth 1.0
    s5 errorbar linestyle 1
    s5 errorbar riser linewidth 1.0
    s5 errorbar riser linestyle 1
    s5 errorbar riser clip off
    s5 errorbar riser clip length 0.100000
    s5 comment "../../rate_num/datfig/no_pb_x_ginter_no_intra/tvnc.amp"
    s5 legend  ""
    s6 hidden false
    s6 type xy
    s6 symbol 0
    s6 symbol size 1.000000
    s6 symbol color 11
    s6 symbol pattern 1
    s6 symbol fill color 11
    s6 symbol fill pattern 0
    s6 symbol linewidth 1.0
    s6 symbol linestyle 1
    s6 symbol char 65
    s6 symbol char font 0
    s6 symbol skip 0
    s6 line type 1
    s6 line linestyle 1
    s6 line linewidth 1.5
    s6 line color 11
    s6 line pattern 1
    s6 baseline type 0
    s6 baseline off
    s6 dropline off
    s6 fill type 0
    s6 fill rule 0
    s6 fill color 1
    s6 fill pattern 1
    s6 avalue off
    s6 avalue type 2
    s6 avalue char size 1.000000
    s6 avalue font 0
    s6 avalue color 1
    s6 avalue rot 0
    s6 avalue format general
    s6 avalue prec 3
    s6 avalue prepend ""
    s6 avalue append ""
    s6 avalue offset 0.000000 , 0.000000
    s6 errorbar on
    s6 errorbar place both
    s6 errorbar color 11
    s6 errorbar pattern 1
    s6 errorbar size 1.000000
    s6 errorbar linewidth 1.0
    s6 errorbar linestyle 1
    s6 errorbar riser linewidth 1.0
    s6 errorbar riser linestyle 1
    s6 errorbar riser clip off
    s6 errorbar riser clip length 0.100000
    s6 comment "../../rate_num/datfig/no_pb_x_ginter_no_intra/tvnc.amp"
    s6 legend  ""
    s7 hidden false
    s7 type xy
    s7 symbol 0
    s7 symbol size 1.000000
    s7 symbol color 10
    s7 symbol pattern 1
    s7 symbol fill color 10
    s7 symbol fill pattern 0
    s7 symbol linewidth 1.0
    s7 symbol linestyle 1
    s7 symbol char 65
    s7 symbol char font 0
    s7 symbol skip 0
    s7 line type 1
    s7 line linestyle 3
    s7 line linewidth 2.0
    s7 line color 10
    s7 line pattern 1
    s7 baseline type 0
    s7 baseline off
    s7 dropline off
    s7 fill type 0
    s7 fill rule 0
    s7 fill color 1
    s7 fill pattern 1
    s7 avalue off
    s7 avalue type 2
    s7 avalue char size 1.000000
    s7 avalue font 0
    s7 avalue color 1
    s7 avalue rot 0
    s7 avalue format general
    s7 avalue prec 3
    s7 avalue prepend ""
    s7 avalue append ""
    s7 avalue offset 0.000000 , 0.000000
    s7 errorbar on
    s7 errorbar place both
    s7 errorbar color 10
    s7 errorbar pattern 1
    s7 errorbar size 1.000000
    s7 errorbar linewidth 1.0
    s7 errorbar linestyle 1
    s7 errorbar riser linewidth 1.0
    s7 errorbar riser linestyle 1
    s7 errorbar riser clip off
    s7 errorbar riser clip length 0.100000
    s7 comment "../../rate_num/datfig/no_pb_x_ginter_no_intra/tvnc.set"
    s7 legend  ""
    s8 hidden false
    s8 type xy
    s8 symbol 0
    s8 symbol size 1.000000
    s8 symbol color 10
    s8 symbol pattern 1
    s8 symbol fill color 10
    s8 symbol fill pattern 0
    s8 symbol linewidth 1.0
    s8 symbol linestyle 1
    s8 symbol char 65
    s8 symbol char font 0
    s8 symbol skip 0
    s8 line type 1
    s8 line linestyle 3
    s8 line linewidth 2.0
    s8 line color 10
    s8 line pattern 1
    s8 baseline type 0
    s8 baseline off
    s8 dropline off
    s8 fill type 0
    s8 fill rule 0
    s8 fill color 1
    s8 fill pattern 1
    s8 avalue off
    s8 avalue type 2
    s8 avalue char size 1.000000
    s8 avalue font 0
    s8 avalue color 1
    s8 avalue rot 0
    s8 avalue format general
    s8 avalue prec 3
    s8 avalue prepend ""
    s8 avalue append ""
    s8 avalue offset 0.000000 , 0.000000
    s8 errorbar on
    s8 errorbar place both
    s8 errorbar color 10
    s8 errorbar pattern 1
    s8 errorbar size 1.000000
    s8 errorbar linewidth 1.0
    s8 errorbar linestyle 1
    s8 errorbar riser linewidth 1.0
    s8 errorbar riser linestyle 1
    s8 errorbar riser clip off
    s8 errorbar riser clip length 0.100000
    s8 comment "../../rate_num/datfig/no_pb_x_ginter_no_intra/tvnc.set"
    s8 legend  ""
    s9 hidden false
    s9 type xy
    s9 symbol 0
    s9 symbol size 1.000000
    s9 symbol color 10
    s9 symbol pattern 1
    s9 symbol fill color 10
    s9 symbol fill pattern 0
    s9 symbol linewidth 1.0
    s9 symbol linestyle 1
    s9 symbol char 65
    s9 symbol char font 0
    s9 symbol skip 0
    s9 line type 1
    s9 line linestyle 3
    s9 line linewidth 2.0
    s9 line color 10
    s9 line pattern 1
    s9 baseline type 0
    s9 baseline off
    s9 dropline off
    s9 fill type 0
    s9 fill rule 0
    s9 fill color 1
    s9 fill pattern 1
    s9 avalue off
    s9 avalue type 2
    s9 avalue char size 1.000000
    s9 avalue font 0
    s9 avalue color 1
    s9 avalue rot 0
    s9 avalue format general
    s9 avalue prec 3
    s9 avalue prepend ""
    s9 avalue append ""
    s9 avalue offset 0.000000 , 0.000000
    s9 errorbar on
    s9 errorbar place both
    s9 errorbar color 10
    s9 errorbar pattern 1
    s9 errorbar size 1.000000
    s9 errorbar linewidth 1.0
    s9 errorbar linestyle 1
    s9 errorbar riser linewidth 1.0
    s9 errorbar riser linestyle 1
    s9 errorbar riser clip off
    s9 errorbar riser clip length 0.100000
    s9 comment "../../rate_num/datfig/no_pb_x_ginter_no_intra/tvnc.set"
    s9 legend  ""
g6 on
g6 hidden false
g6 type XY
g6 stacked false
g6 bar hgap 0.000000
g6 fixedpoint off
g6 fixedpoint type 0
g6 fixedpoint xy 0.000000, 0.000000
g6 fixedpoint format general general
g6 fixedpoint prec 6, 6
with g6
    world 0, 0, 30, 14
    stack world 0, 0, 0, 0
    znorm 1
    view 0.480000, 0.759000, 0.730000, 0.779000
    title ""
    title font 0
    title size 1.500000
    title color 1
    subtitle ""
    subtitle font 0
    subtitle size 1.000000
    subtitle color 1
    xaxes scale Normal
    yaxes scale Normal
    xaxes invert off
    yaxes invert off
    xaxis  off
    yaxis  off
    altxaxis  off
    altyaxis  off
    legend on
    legend loctype view
    legend 0.85, 0.8
    legend box color 1
    legend box pattern 1
    legend box linewidth 1.0
    legend box linestyle 1
    legend box fill color 0
    legend box fill pattern 1
    legend font 0
    legend char size 1.000000
    legend color 1
    legend length 4
    legend vgap 1
    legend hgap 1
    legend invert false
    frame type 1
    frame linestyle 1
    frame linewidth 1.0
    frame color 1
    frame pattern 0
    frame background color 0
    frame background pattern 0
g7 on
g7 hidden false
g7 type XY
g7 stacked false
g7 bar hgap 0.000000
g7 fixedpoint off
g7 fixedpoint type 0
g7 fixedpoint xy 0.000000, 0.000000
g7 fixedpoint format general general
g7 fixedpoint prec 6, 6
with g7
    world 0, -0.5, 30, 90
    stack world 0, 0, 0, 0
    znorm 1
    view 0.480000, 0.780000, 0.730000, 0.940000
    title ""
    title font 0
    title size 1.500000
    title color 1
    subtitle ""
    subtitle font 0
    subtitle size 1.000000
    subtitle color 1
    xaxes scale Normal
    yaxes scale Normal
    xaxes invert off
    yaxes invert off
    xaxis  on
    xaxis  type zero false
    xaxis  offset 0.000000 , 0.000000
    xaxis  bar on
    xaxis  bar color 1
    xaxis  bar linestyle 1
    xaxis  bar linewidth 1.0
    xaxis  label ""
    xaxis  label layout para
    xaxis  label place auto
    xaxis  label char size 1.000000
    xaxis  label font 4
    xaxis  label color 1
    xaxis  label place normal
    xaxis  tick on
    xaxis  tick major 10
    xaxis  tick minor ticks 4
    xaxis  tick default 6
    xaxis  tick place rounded true
    xaxis  tick out
    xaxis  tick major size 0.460000
    xaxis  tick major color 1
    xaxis  tick major linewidth 1.0
    xaxis  tick major linestyle 1
    xaxis  tick major grid off
    xaxis  tick minor color 1
    xaxis  tick minor linewidth 1.0
    xaxis  tick minor linestyle 1
    xaxis  tick minor grid off
    xaxis  tick minor size 0.200000
    xaxis  ticklabel on
    xaxis  ticklabel format general
    xaxis  ticklabel prec 5
    xaxis  ticklabel formula ""
    xaxis  ticklabel append ""
    xaxis  ticklabel prepend ""
    xaxis  ticklabel angle 0
    xaxis  ticklabel skip 0
    xaxis  ticklabel stagger 0
    xaxis  ticklabel place normal
    xaxis  ticklabel offset auto
    xaxis  ticklabel offset 0.000000 , 0.010000
    xaxis  ticklabel start type spec
    xaxis  ticklabel start 2000.000000
    xaxis  ticklabel stop type auto
    xaxis  ticklabel stop 0.000000
    xaxis  ticklabel char size 1.000000
    xaxis  ticklabel font 4
    xaxis  ticklabel color 1
    xaxis  tick place normal
    xaxis  tick spec type none
    yaxis  on
    yaxis  type zero false
    yaxis  offset 0.000000 , 0.000000
    yaxis  bar on
    yaxis  bar color 1
    yaxis  bar linestyle 1
    yaxis  bar linewidth 1.0
    yaxis  label ""
    yaxis  label layout para
    yaxis  label place auto
    yaxis  label char size 1.000000
    yaxis  label font 4
    yaxis  label color 1
    yaxis  label place normal
    yaxis  tick on
    yaxis  tick major 30
    yaxis  tick minor ticks 2
    yaxis  tick default 6
    yaxis  tick place rounded true
    yaxis  tick out
    yaxis  tick major size 0.460000
    yaxis  tick major color 1
    yaxis  tick major linewidth 1.0
    yaxis  tick major linestyle 1
    yaxis  tick major grid off
    yaxis  tick minor color 1
    yaxis  tick minor linewidth 1.0
    yaxis  tick minor linestyle 1
    yaxis  tick minor grid off
    yaxis  tick minor size 0.200000
    yaxis  ticklabel on
    yaxis  ticklabel format general
    yaxis  ticklabel prec 5
    yaxis  ticklabel formula ""
    yaxis  ticklabel append ""
    yaxis  ticklabel prepend ""
    yaxis  ticklabel angle 0
    yaxis  ticklabel skip 0
    yaxis  ticklabel stagger 0
    yaxis  ticklabel place normal
    yaxis  ticklabel offset auto
    yaxis  ticklabel offset 0.000000 , 0.010000
    yaxis  ticklabel start type spec
    yaxis  ticklabel start 2000.000000
    yaxis  ticklabel stop type auto
    yaxis  ticklabel stop 0.000000
    yaxis  ticklabel char size 1.000000
    yaxis  ticklabel font 4
    yaxis  ticklabel color 1
    yaxis  tick place normal
    yaxis  tick spec type none
    altxaxis  off
    altyaxis  off
    legend on
    legend loctype view
    legend 0.54, 0.69
    legend box color 1
    legend box pattern 0
    legend box linewidth 1.0
    legend box linestyle 0
    legend box fill color 0
    legend box fill pattern 1
    legend font 4
    legend char size 0.780000
    legend color 1
    legend length 3
    legend vgap 1
    legend hgap 1
    legend invert false
    frame type 1
    frame linestyle 1
    frame linewidth 1.0
    frame color 1
    frame pattern 1
    frame background color 0
    frame background pattern 0
    s0 hidden false
    s0 type xydy
    s0 symbol 1
    s0 symbol size 0.210000
    s0 symbol color 1
    s0 symbol pattern 1
    s0 symbol fill color 1
    s0 symbol fill pattern 1
    s0 symbol linewidth 1.0
    s0 symbol linestyle 1
    s0 symbol char 65
    s0 symbol char font 0
    s0 symbol skip 0
    s0 line type 0
    s0 line linestyle 1
    s0 line linewidth 1.0
    s0 line color 1
    s0 line pattern 1
    s0 baseline type 0
    s0 baseline off
    s0 dropline off
    s0 fill type 0
    s0 fill rule 0
    s0 fill color 1
    s0 fill pattern 1
    s0 avalue off
    s0 avalue type 2
    s0 avalue char size 1.000000
    s0 avalue font 0
    s0 avalue color 1
    s0 avalue rot 0
    s0 avalue format general
    s0 avalue prec 3
    s0 avalue prepend ""
    s0 avalue append ""
    s0 avalue offset 0.000000 , 0.000000
    s0 errorbar on
    s0 errorbar place both
    s0 errorbar color 1
    s0 errorbar pattern 1
    s0 errorbar size 0.170000
    s0 errorbar linewidth 1.0
    s0 errorbar linestyle 1
    s0 errorbar riser linewidth 1.0
    s0 errorbar riser linestyle 1
    s0 errorbar riser clip off
    s0 errorbar riser clip length 0.100000
    s0 comment "c227/tperst.col"
    s0 legend  ""
    s1 hidden false
    s1 type xydy
    s1 symbol 1
    s1 symbol size 0.210000
    s1 symbol color 1
    s1 symbol pattern 1
    s1 symbol fill color 1
    s1 symbol fill pattern 0
    s1 symbol linewidth 1.0
    s1 symbol linestyle 1
    s1 symbol char 65
    s1 symbol char font 0
    s1 symbol skip 0
    s1 line type 0
    s1 line linestyle 1
    s1 line linewidth 1.0
    s1 line color 1
    s1 line pattern 1
    s1 baseline type 0
    s1 baseline off
    s1 dropline off
    s1 fill type 0
    s1 fill rule 0
    s1 fill color 1
    s1 fill pattern 1
    s1 avalue off
    s1 avalue type 2
    s1 avalue char size 1.000000
    s1 avalue font 0
    s1 avalue color 1
    s1 avalue rot 0
    s1 avalue format general
    s1 avalue prec 3
    s1 avalue prepend ""
    s1 avalue append ""
    s1 avalue offset 0.000000 , 0.000000
    s1 errorbar on
    s1 errorbar place both
    s1 errorbar color 1
    s1 errorbar pattern 1
    s1 errorbar size 0.170000
    s1 errorbar linewidth 1.0
    s1 errorbar linestyle 1
    s1 errorbar riser linewidth 1.0
    s1 errorbar riser linestyle 1
    s1 errorbar riser clip off
    s1 errorbar riser clip length 0.100000
    s1 comment "c2281/mtper.mfr"
    s1 legend  ""
    s2 hidden false
    s2 type xy
    s2 symbol 0
    s2 symbol size 1.000000
    s2 symbol color 11
    s2 symbol pattern 1
    s2 symbol fill color 11
    s2 symbol fill pattern 0
    s2 symbol linewidth 1.0
    s2 symbol linestyle 1
    s2 symbol char 65
    s2 symbol char font 0
    s2 symbol skip 0
    s2 line type 1
    s2 line linestyle 1
    s2 line linewidth 1.5
    s2 line color 11
    s2 line pattern 1
    s2 baseline type 0
    s2 baseline off
    s2 dropline off
    s2 fill type 0
    s2 fill rule 0
    s2 fill color 1
    s2 fill pattern 1
    s2 avalue off
    s2 avalue type 2
    s2 avalue char size 1.000000
    s2 avalue font 0
    s2 avalue color 1
    s2 avalue rot 0
    s2 avalue format general
    s2 avalue prec 3
    s2 avalue prepend ""
    s2 avalue append ""
    s2 avalue offset 0.000000 , 0.000000
    s2 errorbar on
    s2 errorbar place both
    s2 errorbar color 11
    s2 errorbar pattern 1
    s2 errorbar size 1.000000
    s2 errorbar linewidth 1.0
    s2 errorbar linestyle 1
    s2 errorbar riser linewidth 1.0
    s2 errorbar riser linestyle 1
    s2 errorbar riser clip off
    s2 errorbar riser clip length 0.100000
    s2 comment "c2281/mtper.mfr"
    s2 legend  ""
    s3 hidden false
    s3 type xy
    s3 symbol 0
    s3 symbol size 1.000000
    s3 symbol color 10
    s3 symbol pattern 1
    s3 symbol fill color 10
    s3 symbol fill pattern 0
    s3 symbol linewidth 1.0
    s3 symbol linestyle 1
    s3 symbol char 65
    s3 symbol char font 0
    s3 symbol skip 0
    s3 line type 1
    s3 line linestyle 3
    s3 line linewidth 2.0
    s3 line color 10
    s3 line pattern 1
    s3 baseline type 0
    s3 baseline off
    s3 dropline off
    s3 fill type 0
    s3 fill rule 0
    s3 fill color 1
    s3 fill pattern 1
    s3 avalue off
    s3 avalue type 2
    s3 avalue char size 1.000000
    s3 avalue font 0
    s3 avalue color 1
    s3 avalue rot 0
    s3 avalue format general
    s3 avalue prec 3
    s3 avalue prepend ""
    s3 avalue append ""
    s3 avalue offset 0.000000 , 0.000000
    s3 errorbar on
    s3 errorbar place both
    s3 errorbar color 10
    s3 errorbar pattern 1
    s3 errorbar size 1.000000
    s3 errorbar linewidth 1.0
    s3 errorbar linestyle 1
    s3 errorbar riser linewidth 1.0
    s3 errorbar riser linestyle 1
    s3 errorbar riser clip off
    s3 errorbar riser clip length 0.100000
    s3 comment "c2281/mtper.mfr"
    s3 legend  ""
g8 on
g8 hidden false
g8 type XY
g8 stacked false
g8 bar hgap 0.000000
g8 fixedpoint off
g8 fixedpoint type 0
g8 fixedpoint xy 0.000000, 0.000000
g8 fixedpoint format general general
g8 fixedpoint prec 6, 6
with g8
    world 0, 0, 30, 14
    stack world 0, 0, 0, 0
    znorm 1
    view 0.480000, 0.320000, 0.730000, 0.480000
    title ""
    title font 0
    title size 1.500000
    title color 1
    subtitle ""
    subtitle font 0
    subtitle size 1.000000
    subtitle color 1
    xaxes scale Normal
    yaxes scale Normal
    xaxes invert off
    yaxes invert off
    xaxis  on
    xaxis  type zero false
    xaxis  offset 0.000000 , 0.000000
    xaxis  bar on
    xaxis  bar color 1
    xaxis  bar linestyle 1
    xaxis  bar linewidth 1.0
    xaxis  label ""
    xaxis  label layout para
    xaxis  label place auto
    xaxis  label char size 1.000000
    xaxis  label font 4
    xaxis  label color 1
    xaxis  label place normal
    xaxis  tick on
    xaxis  tick major 10
    xaxis  tick minor ticks 4
    xaxis  tick default 6
    xaxis  tick place rounded true
    xaxis  tick out
    xaxis  tick major size 0.460000
    xaxis  tick major color 1
    xaxis  tick major linewidth 1.0
    xaxis  tick major linestyle 1
    xaxis  tick major grid off
    xaxis  tick minor color 1
    xaxis  tick minor linewidth 1.0
    xaxis  tick minor linestyle 1
    xaxis  tick minor grid off
    xaxis  tick minor size 0.200000
    xaxis  ticklabel on
    xaxis  ticklabel format general
    xaxis  ticklabel prec 5
    xaxis  ticklabel formula ""
    xaxis  ticklabel append ""
    xaxis  ticklabel prepend ""
    xaxis  ticklabel angle 0
    xaxis  ticklabel skip 0
    xaxis  ticklabel stagger 0
    xaxis  ticklabel place normal
    xaxis  ticklabel offset auto
    xaxis  ticklabel offset 0.000000 , 0.010000
    xaxis  ticklabel start type spec
    xaxis  ticklabel start 2000.000000
    xaxis  ticklabel stop type auto
    xaxis  ticklabel stop 0.000000
    xaxis  ticklabel char size 1.000000
    xaxis  ticklabel font 4
    xaxis  ticklabel color 1
    xaxis  tick place normal
    xaxis  tick spec type none
    yaxis  on
    yaxis  type zero false
    yaxis  offset 0.000000 , 0.000000
    yaxis  bar on
    yaxis  bar color 1
    yaxis  bar linestyle 1
    yaxis  bar linewidth 1.0
    yaxis  label ""
    yaxis  label layout para
    yaxis  label place auto
    yaxis  label char size 1.000000
    yaxis  label font 4
    yaxis  label color 1
    yaxis  label place normal
    yaxis  tick on
    yaxis  tick major 5
    yaxis  tick minor ticks 4
    yaxis  tick default 6
    yaxis  tick place rounded true
    yaxis  tick out
    yaxis  tick major size 0.460000
    yaxis  tick major color 1
    yaxis  tick major linewidth 1.0
    yaxis  tick major linestyle 1
    yaxis  tick major grid off
    yaxis  tick minor color 1
    yaxis  tick minor linewidth 1.0
    yaxis  tick minor linestyle 1
    yaxis  tick minor grid off
    yaxis  tick minor size 0.200000
    yaxis  ticklabel on
    yaxis  ticklabel format general
    yaxis  ticklabel prec 5
    yaxis  ticklabel formula ""
    yaxis  ticklabel append ""
    yaxis  ticklabel prepend ""
    yaxis  ticklabel angle 0
    yaxis  ticklabel skip 0
    yaxis  ticklabel stagger 0
    yaxis  ticklabel place normal
    yaxis  ticklabel offset auto
    yaxis  ticklabel offset 0.000000 , 0.010000
    yaxis  ticklabel start type spec
    yaxis  ticklabel start 2000.000000
    yaxis  ticklabel stop type auto
    yaxis  ticklabel stop 0.000000
    yaxis  ticklabel char size 1.000000
    yaxis  ticklabel font 4
    yaxis  ticklabel color 1
    yaxis  tick place normal
    yaxis  tick spec type none
    altxaxis  off
    altyaxis  off
    legend on
    legend loctype view
    legend 0.85, 0.8
    legend box color 1
    legend box pattern 1
    legend box linewidth 1.0
    legend box linestyle 1
    legend box fill color 0
    legend box fill pattern 1
    legend font 0
    legend char size 1.000000
    legend color 1
    legend length 4
    legend vgap 1
    legend hgap 1
    legend invert false
    frame type 1
    frame linestyle 1
    frame linewidth 1.0
    frame color 1
    frame pattern 1
    frame background color 0
    frame background pattern 0
    s0 hidden false
    s0 type xydy
    s0 symbol 1
    s0 symbol size 0.210000
    s0 symbol color 1
    s0 symbol pattern 1
    s0 symbol fill color 1
    s0 symbol fill pattern 1
    s0 symbol linewidth 1.0
    s0 symbol linestyle 1
    s0 symbol char 65
    s0 symbol char font 0
    s0 symbol skip 0
    s0 line type 0
    s0 line linestyle 1
    s0 line linewidth 1.0
    s0 line color 1
    s0 line pattern 1
    s0 baseline type 0
    s0 baseline off
    s0 dropline off
    s0 fill type 0
    s0 fill rule 0
    s0 fill color 1
    s0 fill pattern 1
    s0 avalue off
    s0 avalue type 2
    s0 avalue char size 1.000000
    s0 avalue font 0
    s0 avalue color 1
    s0 avalue rot 0
    s0 avalue format general
    s0 avalue prec 3
    s0 avalue prepend ""
    s0 avalue append ""
    s0 avalue offset 0.000000 , 0.000000
    s0 errorbar on
    s0 errorbar place both
    s0 errorbar color 1
    s0 errorbar pattern 1
    s0 errorbar size 0.170000
    s0 errorbar linewidth 1.0
    s0 errorbar linestyle 1
    s0 errorbar riser linewidth 1.0
    s0 errorbar riser linestyle 1
    s0 errorbar riser clip off
    s0 errorbar riser clip length 0.100000
    s0 comment "c227/tperst.col"
    s0 legend  ""
    s1 hidden false
    s1 type xy
    s1 symbol 0
    s1 symbol size 1.000000
    s1 symbol color 11
    s1 symbol pattern 1
    s1 symbol fill color 11
    s1 symbol fill pattern 0
    s1 symbol linewidth 1.0
    s1 symbol linestyle 1
    s1 symbol char 65
    s1 symbol char font 0
    s1 symbol skip 0
    s1 line type 1
    s1 line linestyle 1
    s1 line linewidth 1.5
    s1 line color 11
    s1 line pattern 1
    s1 baseline type 0
    s1 baseline off
    s1 dropline off
    s1 fill type 0
    s1 fill rule 0
    s1 fill color 1
    s1 fill pattern 1
    s1 avalue off
    s1 avalue type 2
    s1 avalue char size 1.000000
    s1 avalue font 0
    s1 avalue color 1
    s1 avalue rot 0
    s1 avalue format general
    s1 avalue prec 3
    s1 avalue prepend ""
    s1 avalue append ""
    s1 avalue offset 0.000000 , 0.000000
    s1 errorbar on
    s1 errorbar place both
    s1 errorbar color 11
    s1 errorbar pattern 1
    s1 errorbar size 1.000000
    s1 errorbar linewidth 1.0
    s1 errorbar linestyle 1
    s1 errorbar riser linewidth 1.0
    s1 errorbar riser linestyle 1
    s1 errorbar riser clip off
    s1 errorbar riser clip length 0.100000
    s1 comment "c227/tperst.col"
    s1 legend  ""
    s2 hidden false
    s2 type xy
    s2 symbol 0
    s2 symbol size 1.000000
    s2 symbol color 10
    s2 symbol pattern 1
    s2 symbol fill color 10
    s2 symbol fill pattern 0
    s2 symbol linewidth 1.0
    s2 symbol linestyle 1
    s2 symbol char 65
    s2 symbol char font 0
    s2 symbol skip 0
    s2 line type 1
    s2 line linestyle 3
    s2 line linewidth 2.0
    s2 line color 10
    s2 line pattern 1
    s2 baseline type 0
    s2 baseline off
    s2 dropline off
    s2 fill type 0
    s2 fill rule 0
    s2 fill color 1
    s2 fill pattern 1
    s2 avalue off
    s2 avalue type 2
    s2 avalue char size 1.000000
    s2 avalue font 0
    s2 avalue color 1
    s2 avalue rot 0
    s2 avalue format general
    s2 avalue prec 3
    s2 avalue prepend ""
    s2 avalue append ""
    s2 avalue offset 0.000000 , 0.000000
    s2 errorbar on
    s2 errorbar place both
    s2 errorbar color 10
    s2 errorbar pattern 1
    s2 errorbar size 1.000000
    s2 errorbar linewidth 1.0
    s2 errorbar linestyle 1
    s2 errorbar riser linewidth 1.0
    s2 errorbar riser linestyle 1
    s2 errorbar riser clip off
    s2 errorbar riser clip length 0.100000
    s2 comment "c227/tperst.col"
    s2 legend  ""
g9 on
g9 hidden false
g9 type XY
g9 stacked false
g9 bar hgap 0.000000
g9 fixedpoint off
g9 fixedpoint type 0
g9 fixedpoint xy 0.000000, 0.000000
g9 fixedpoint format general general
g9 fixedpoint prec 6, 6
with g9
    world 0, -0.4, 30, 30
    stack world 0, 0, 0, 0
    znorm 1
    view 0.480000, 0.550000, 0.730000, 0.710000
    title ""
    title font 0
    title size 1.500000
    title color 1
    subtitle ""
    subtitle font 0
    subtitle size 1.000000
    subtitle color 1
    xaxes scale Normal
    yaxes scale Normal
    xaxes invert off
    yaxes invert off
    xaxis  on
    xaxis  type zero false
    xaxis  offset 0.000000 , 0.000000
    xaxis  bar on
    xaxis  bar color 1
    xaxis  bar linestyle 1
    xaxis  bar linewidth 1.0
    xaxis  label ""
    xaxis  label layout para
    xaxis  label place auto
    xaxis  label char size 1.000000
    xaxis  label font 4
    xaxis  label color 1
    xaxis  label place normal
    xaxis  tick on
    xaxis  tick major 10
    xaxis  tick minor ticks 4
    xaxis  tick default 6
    xaxis  tick place rounded true
    xaxis  tick out
    xaxis  tick major size 0.460000
    xaxis  tick major color 1
    xaxis  tick major linewidth 1.0
    xaxis  tick major linestyle 1
    xaxis  tick major grid off
    xaxis  tick minor color 1
    xaxis  tick minor linewidth 1.0
    xaxis  tick minor linestyle 1
    xaxis  tick minor grid off
    xaxis  tick minor size 0.200000
    xaxis  ticklabel on
    xaxis  ticklabel format general
    xaxis  ticklabel prec 5
    xaxis  ticklabel formula ""
    xaxis  ticklabel append ""
    xaxis  ticklabel prepend ""
    xaxis  ticklabel angle 0
    xaxis  ticklabel skip 0
    xaxis  ticklabel stagger 0
    xaxis  ticklabel place normal
    xaxis  ticklabel offset auto
    xaxis  ticklabel offset 0.000000 , 0.010000
    xaxis  ticklabel start type spec
    xaxis  ticklabel start 2000.000000
    xaxis  ticklabel stop type auto
    xaxis  ticklabel stop 0.000000
    xaxis  ticklabel char size 1.000000
    xaxis  ticklabel font 4
    xaxis  ticklabel color 1
    xaxis  tick place normal
    xaxis  tick spec type none
    yaxis  on
    yaxis  type zero false
    yaxis  offset 0.000000 , 0.000000
    yaxis  bar on
    yaxis  bar color 1
    yaxis  bar linestyle 1
    yaxis  bar linewidth 1.0
    yaxis  label ""
    yaxis  label layout para
    yaxis  label place auto
    yaxis  label char size 1.000000
    yaxis  label font 4
    yaxis  label color 1
    yaxis  label place normal
    yaxis  tick on
    yaxis  tick major 15
    yaxis  tick minor ticks 2
    yaxis  tick default 6
    yaxis  tick place rounded true
    yaxis  tick out
    yaxis  tick major size 0.460000
    yaxis  tick major color 1
    yaxis  tick major linewidth 1.0
    yaxis  tick major linestyle 1
    yaxis  tick major grid off
    yaxis  tick minor color 1
    yaxis  tick minor linewidth 1.0
    yaxis  tick minor linestyle 1
    yaxis  tick minor grid off
    yaxis  tick minor size 0.200000
    yaxis  ticklabel on
    yaxis  ticklabel format general
    yaxis  ticklabel prec 5
    yaxis  ticklabel formula ""
    yaxis  ticklabel append ""
    yaxis  ticklabel prepend ""
    yaxis  ticklabel angle 0
    yaxis  ticklabel skip 0
    yaxis  ticklabel stagger 0
    yaxis  ticklabel place normal
    yaxis  ticklabel offset auto
    yaxis  ticklabel offset 0.000000 , 0.010000
    yaxis  ticklabel start type spec
    yaxis  ticklabel start 2000.000000
    yaxis  ticklabel stop type auto
    yaxis  ticklabel stop 0.000000
    yaxis  ticklabel char size 1.000000
    yaxis  ticklabel font 4
    yaxis  ticklabel color 1
    yaxis  tick place normal
    yaxis  tick spec type none
    altxaxis  off
    altyaxis  off
    legend on
    legend loctype view
    legend 0.48, 0.3
    legend box color 1
    legend box pattern 0
    legend box linewidth 1.0
    legend box linestyle 0
    legend box fill color 0
    legend box fill pattern 1
    legend font 4
    legend char size 0.780000
    legend color 1
    legend length 3
    legend vgap 1
    legend hgap 1
    legend invert false
    frame type 1
    frame linestyle 1
    frame linewidth 1.0
    frame color 1
    frame pattern 1
    frame background color 0
    frame background pattern 0
    s0 hidden false
    s0 type xydy
    s0 symbol 0
    s0 symbol size 0.210000
    s0 symbol color 1
    s0 symbol pattern 1
    s0 symbol fill color 1
    s0 symbol fill pattern 1
    s0 symbol linewidth 1.0
    s0 symbol linestyle 1
    s0 symbol char 65
    s0 symbol char font 0
    s0 symbol skip 0
    s0 line type 0
    s0 line linestyle 1
    s0 line linewidth 1.0
    s0 line color 1
    s0 line pattern 1
    s0 baseline type 0
    s0 baseline off
    s0 dropline off
    s0 fill type 0
    s0 fill rule 0
    s0 fill color 1
    s0 fill pattern 1
    s0 avalue off
    s0 avalue type 2
    s0 avalue char size 1.000000
    s0 avalue font 0
    s0 avalue color 1
    s0 avalue rot 0
    s0 avalue format general
    s0 avalue prec 3
    s0 avalue prepend ""
    s0 avalue append ""
    s0 avalue offset 0.000000 , 0.000000
    s0 errorbar on
    s0 errorbar place both
    s0 errorbar color 1
    s0 errorbar pattern 1
    s0 errorbar size 0.170000
    s0 errorbar linewidth 1.0
    s0 errorbar linestyle 0
    s0 errorbar riser linewidth 1.0
    s0 errorbar riser linestyle 0
    s0 errorbar riser clip off
    s0 errorbar riser clip length 0.100000
    s0 comment "c227/tperst.col"
    s0 legend  ""
    s1 hidden false
    s1 type xydy
    s1 symbol 0
    s1 symbol size 0.210000
    s1 symbol color 7
    s1 symbol pattern 1
    s1 symbol fill color 7
    s1 symbol fill pattern 0
    s1 symbol linewidth 1.0
    s1 symbol linestyle 1
    s1 symbol char 65
    s1 symbol char font 0
    s1 symbol skip 0
    s1 line type 0
    s1 line linestyle 1
    s1 line linewidth 1.0
    s1 line color 7
    s1 line pattern 1
    s1 baseline type 0
    s1 baseline off
    s1 dropline off
    s1 fill type 0
    s1 fill rule 0
    s1 fill color 1
    s1 fill pattern 1
    s1 avalue off
    s1 avalue type 2
    s1 avalue char size 1.000000
    s1 avalue font 0
    s1 avalue color 1
    s1 avalue rot 0
    s1 avalue format general
    s1 avalue prec 3
    s1 avalue prepend ""
    s1 avalue append ""
    s1 avalue offset 0.000000 , 0.000000
    s1 errorbar on
    s1 errorbar place both
    s1 errorbar color 7
    s1 errorbar pattern 1
    s1 errorbar size 0.170000
    s1 errorbar linewidth 1.0
    s1 errorbar linestyle 0
    s1 errorbar riser linewidth 1.0
    s1 errorbar riser linestyle 0
    s1 errorbar riser clip off
    s1 errorbar riser clip length 0.100000
    s1 comment "c2281/mtper.mfr"
    s1 legend  ""
    s2 hidden false
    s2 type xydy
    s2 symbol 1
    s2 symbol size 0.210000
    s2 symbol color 1
    s2 symbol pattern 1
    s2 symbol fill color 1
    s2 symbol fill pattern 1
    s2 symbol linewidth 1.0
    s2 symbol linestyle 1
    s2 symbol char 65
    s2 symbol char font 0
    s2 symbol skip 0
    s2 line type 0
    s2 line linestyle 1
    s2 line linewidth 1.0
    s2 line color 3
    s2 line pattern 1
    s2 baseline type 0
    s2 baseline off
    s2 dropline off
    s2 fill type 0
    s2 fill rule 0
    s2 fill color 1
    s2 fill pattern 1
    s2 avalue off
    s2 avalue type 2
    s2 avalue char size 1.000000
    s2 avalue font 0
    s2 avalue color 1
    s2 avalue rot 0
    s2 avalue format general
    s2 avalue prec 3
    s2 avalue prepend ""
    s2 avalue append ""
    s2 avalue offset 0.000000 , 0.000000
    s2 errorbar on
    s2 errorbar place both
    s2 errorbar color 1
    s2 errorbar pattern 1
    s2 errorbar size 0.180000
    s2 errorbar linewidth 1.0
    s2 errorbar linestyle 1
    s2 errorbar riser linewidth 1.0
    s2 errorbar riser linestyle 1
    s2 errorbar riser clip off
    s2 errorbar riser clip length 0.100000
    s2 comment "dat_qsub/no_pb_x_ginter_intra_I0/cmt.wsk"
    s2 legend  ""
    s3 hidden false
    s3 type xydy
    s3 symbol 1
    s3 symbol size 0.210000
    s3 symbol color 7
    s3 symbol pattern 1
    s3 symbol fill color 7
    s3 symbol fill pattern 0
    s3 symbol linewidth 1.0
    s3 symbol linestyle 1
    s3 symbol char 65
    s3 symbol char font 0
    s3 symbol skip 0
    s3 line type 0
    s3 line linestyle 1
    s3 line linewidth 1.0
    s3 line color 15
    s3 line pattern 1
    s3 baseline type 0
    s3 baseline off
    s3 dropline off
    s3 fill type 0
    s3 fill rule 0
    s3 fill color 1
    s3 fill pattern 1
    s3 avalue off
    s3 avalue type 2
    s3 avalue char size 1.000000
    s3 avalue font 0
    s3 avalue color 1
    s3 avalue rot 0
    s3 avalue format general
    s3 avalue prec 3
    s3 avalue prepend ""
    s3 avalue append ""
    s3 avalue offset 0.000000 , 0.000000
    s3 errorbar on
    s3 errorbar place both
    s3 errorbar color 7
    s3 errorbar pattern 1
    s3 errorbar size 0.180000
    s3 errorbar linewidth 1.0
    s3 errorbar linestyle 1
    s3 errorbar riser linewidth 1.0
    s3 errorbar riser linestyle 1
    s3 errorbar riser clip off
    s3 errorbar riser clip length 0.100000
    s3 comment "dat_qsub/no_pb_x_ginter_intra_I0/cmt.wsk"
    s3 legend  ""
    s4 hidden false
    s4 type xy
    s4 symbol 0
    s4 symbol size 1.000000
    s4 symbol color 11
    s4 symbol pattern 1
    s4 symbol fill color 11
    s4 symbol fill pattern 0
    s4 symbol linewidth 1.0
    s4 symbol linestyle 1
    s4 symbol char 65
    s4 symbol char font 0
    s4 symbol skip 0
    s4 line type 1
    s4 line linestyle 1
    s4 line linewidth 1.5
    s4 line color 11
    s4 line pattern 1
    s4 baseline type 0
    s4 baseline off
    s4 dropline off
    s4 fill type 0
    s4 fill rule 0
    s4 fill color 1
    s4 fill pattern 1
    s4 avalue off
    s4 avalue type 2
    s4 avalue char size 1.000000
    s4 avalue font 0
    s4 avalue color 1
    s4 avalue rot 0
    s4 avalue format general
    s4 avalue prec 3
    s4 avalue prepend ""
    s4 avalue append ""
    s4 avalue offset 0.000000 , 0.000000
    s4 errorbar on
    s4 errorbar place both
    s4 errorbar color 11
    s4 errorbar pattern 1
    s4 errorbar size 1.000000
    s4 errorbar linewidth 1.0
    s4 errorbar linestyle 1
    s4 errorbar riser linewidth 1.0
    s4 errorbar riser linestyle 1
    s4 errorbar riser clip off
    s4 errorbar riser clip length 0.100000
    s4 comment "dat_qsub/no_pb_x_ginter_no_intra_I0/cmt.wsk_amp_ct"
    s4 legend  ""
g10 on
g10 hidden false
g10 type XY
g10 stacked false
g10 bar hgap 0.000000
g10 fixedpoint off
g10 fixedpoint type 0
g10 fixedpoint xy 0.000000, 0.000000
g10 fixedpoint format general general
g10 fixedpoint prec 6, 6
with g10
    world 0, -0.4, 30, 60
    stack world 0, 0, 0, 0
    znorm 1
    view 0.480000, 0.090000, 0.730000, 0.250000
    title ""
    title font 0
    title size 1.500000
    title color 1
    subtitle ""
    subtitle font 0
    subtitle size 1.000000
    subtitle color 1
    xaxes scale Normal
    yaxes scale Normal
    xaxes invert off
    yaxes invert off
    xaxis  on
    xaxis  type zero false
    xaxis  offset 0.000000 , 0.000000
    xaxis  bar on
    xaxis  bar color 1
    xaxis  bar linestyle 1
    xaxis  bar linewidth 1.0
    xaxis  label ""
    xaxis  label layout para
    xaxis  label place auto
    xaxis  label char size 1.000000
    xaxis  label font 4
    xaxis  label color 1
    xaxis  label place normal
    xaxis  tick on
    xaxis  tick major 10
    xaxis  tick minor ticks 4
    xaxis  tick default 6
    xaxis  tick place rounded true
    xaxis  tick out
    xaxis  tick major size 0.460000
    xaxis  tick major color 1
    xaxis  tick major linewidth 1.0
    xaxis  tick major linestyle 1
    xaxis  tick major grid off
    xaxis  tick minor color 1
    xaxis  tick minor linewidth 1.0
    xaxis  tick minor linestyle 1
    xaxis  tick minor grid off
    xaxis  tick minor size 0.200000
    xaxis  ticklabel on
    xaxis  ticklabel format general
    xaxis  ticklabel prec 5
    xaxis  ticklabel formula ""
    xaxis  ticklabel append ""
    xaxis  ticklabel prepend ""
    xaxis  ticklabel angle 0
    xaxis  ticklabel skip 0
    xaxis  ticklabel stagger 0
    xaxis  ticklabel place normal
    xaxis  ticklabel offset auto
    xaxis  ticklabel offset 0.000000 , 0.010000
    xaxis  ticklabel start type spec
    xaxis  ticklabel start 2000.000000
    xaxis  ticklabel stop type auto
    xaxis  ticklabel stop 0.000000
    xaxis  ticklabel char size 1.000000
    xaxis  ticklabel font 4
    xaxis  ticklabel color 1
    xaxis  tick place normal
    xaxis  tick spec type none
    yaxis  on
    yaxis  type zero false
    yaxis  offset 0.000000 , 0.000000
    yaxis  bar on
    yaxis  bar color 1
    yaxis  bar linestyle 1
    yaxis  bar linewidth 1.0
    yaxis  label ""
    yaxis  label layout para
    yaxis  label place auto
    yaxis  label char size 1.000000
    yaxis  label font 4
    yaxis  label color 1
    yaxis  label place normal
    yaxis  tick on
    yaxis  tick major 20
    yaxis  tick minor ticks 3
    yaxis  tick default 6
    yaxis  tick place rounded true
    yaxis  tick out
    yaxis  tick major size 0.460000
    yaxis  tick major color 1
    yaxis  tick major linewidth 1.0
    yaxis  tick major linestyle 1
    yaxis  tick major grid off
    yaxis  tick minor color 1
    yaxis  tick minor linewidth 1.0
    yaxis  tick minor linestyle 1
    yaxis  tick minor grid off
    yaxis  tick minor size 0.200000
    yaxis  ticklabel on
    yaxis  ticklabel format general
    yaxis  ticklabel prec 5
    yaxis  ticklabel formula ""
    yaxis  ticklabel append ""
    yaxis  ticklabel prepend ""
    yaxis  ticklabel angle 0
    yaxis  ticklabel skip 0
    yaxis  ticklabel stagger 0
    yaxis  ticklabel place normal
    yaxis  ticklabel offset auto
    yaxis  ticklabel offset 0.000000 , 0.010000
    yaxis  ticklabel start type spec
    yaxis  ticklabel start 2000.000000
    yaxis  ticklabel stop type auto
    yaxis  ticklabel stop 0.000000
    yaxis  ticklabel char size 1.000000
    yaxis  ticklabel font 4
    yaxis  ticklabel color 1
    yaxis  tick place normal
    yaxis  tick spec type none
    altxaxis  off
    altyaxis  off
    legend on
    legend loctype view
    legend 0.48, 0.3
    legend box color 1
    legend box pattern 0
    legend box linewidth 1.0
    legend box linestyle 0
    legend box fill color 0
    legend box fill pattern 1
    legend font 4
    legend char size 0.780000
    legend color 1
    legend length 3
    legend vgap 1
    legend hgap 1
    legend invert false
    frame type 1
    frame linestyle 1
    frame linewidth 1.0
    frame color 1
    frame pattern 1
    frame background color 0
    frame background pattern 0
    s0 hidden false
    s0 type xydy
    s0 symbol 1
    s0 symbol size 0.210000
    s0 symbol color 1
    s0 symbol pattern 1
    s0 symbol fill color 1
    s0 symbol fill pattern 1
    s0 symbol linewidth 1.0
    s0 symbol linestyle 1
    s0 symbol char 65
    s0 symbol char font 0
    s0 symbol skip 0
    s0 line type 0
    s0 line linestyle 1
    s0 line linewidth 1.0
    s0 line color 1
    s0 line pattern 1
    s0 baseline type 0
    s0 baseline off
    s0 dropline off
    s0 fill type 0
    s0 fill rule 0
    s0 fill color 1
    s0 fill pattern 1
    s0 avalue off
    s0 avalue type 2
    s0 avalue char size 1.000000
    s0 avalue font 0
    s0 avalue color 1
    s0 avalue rot 0
    s0 avalue format general
    s0 avalue prec 3
    s0 avalue prepend ""
    s0 avalue append ""
    s0 avalue offset 0.000000 , 0.000000
    s0 errorbar on
    s0 errorbar place both
    s0 errorbar color 1
    s0 errorbar pattern 1
    s0 errorbar size 0.170000
    s0 errorbar linewidth 1.0
    s0 errorbar linestyle 1
    s0 errorbar riser linewidth 1.0
    s0 errorbar riser linestyle 1
    s0 errorbar riser clip off
    s0 errorbar riser clip length 0.100000
    s0 comment "c227/tperst.col"
    s0 legend  ""
    s1 hidden false
    s1 type xydy
    s1 symbol 1
    s1 symbol size 0.210000
    s1 symbol color 7
    s1 symbol pattern 1
    s1 symbol fill color 7
    s1 symbol fill pattern 0
    s1 symbol linewidth 1.0
    s1 symbol linestyle 1
    s1 symbol char 65
    s1 symbol char font 0
    s1 symbol skip 0
    s1 line type 0
    s1 line linestyle 1
    s1 line linewidth 1.0
    s1 line color 7
    s1 line pattern 1
    s1 baseline type 0
    s1 baseline off
    s1 dropline off
    s1 fill type 0
    s1 fill rule 0
    s1 fill color 1
    s1 fill pattern 1
    s1 avalue off
    s1 avalue type 2
    s1 avalue char size 1.000000
    s1 avalue font 0
    s1 avalue color 1
    s1 avalue rot 0
    s1 avalue format general
    s1 avalue prec 3
    s1 avalue prepend ""
    s1 avalue append ""
    s1 avalue offset 0.000000 , 0.000000
    s1 errorbar on
    s1 errorbar place both
    s1 errorbar color 7
    s1 errorbar pattern 1
    s1 errorbar size 0.170000
    s1 errorbar linewidth 1.0
    s1 errorbar linestyle 1
    s1 errorbar riser linewidth 1.0
    s1 errorbar riser linestyle 1
    s1 errorbar riser clip off
    s1 errorbar riser clip length 0.100000
    s1 comment "c2281/mtper.mfr"
    s1 legend  ""
    s2 hidden false
    s2 type xydy
    s2 symbol 0
    s2 symbol size 0.210000
    s2 symbol color 1
    s2 symbol pattern 1
    s2 symbol fill color 1
    s2 symbol fill pattern 1
    s2 symbol linewidth 1.0
    s2 symbol linestyle 1
    s2 symbol char 65
    s2 symbol char font 0
    s2 symbol skip 0
    s2 line type 0
    s2 line linestyle 1
    s2 line linewidth 1.0
    s2 line color 1
    s2 line pattern 1
    s2 baseline type 0
    s2 baseline off
    s2 dropline off
    s2 fill type 0
    s2 fill rule 0
    s2 fill color 1
    s2 fill pattern 1
    s2 avalue off
    s2 avalue type 2
    s2 avalue char size 1.000000
    s2 avalue font 0
    s2 avalue color 1
    s2 avalue rot 0
    s2 avalue format general
    s2 avalue prec 3
    s2 avalue prepend ""
    s2 avalue append ""
    s2 avalue offset 0.000000 , 0.000000
    s2 errorbar on
    s2 errorbar place both
    s2 errorbar color 1
    s2 errorbar pattern 1
    s2 errorbar size 0.180000
    s2 errorbar linewidth 1.0
    s2 errorbar linestyle 0
    s2 errorbar riser linewidth 1.0
    s2 errorbar riser linestyle 0
    s2 errorbar riser clip off
    s2 errorbar riser clip length 0.100000
    s2 comment "dat_qsub/no_pb_x_ginter_intra_I0/cmt.wsk"
    s2 legend  ""
    s3 hidden false
    s3 type xydy
    s3 symbol 0
    s3 symbol size 0.210000
    s3 symbol color 7
    s3 symbol pattern 1
    s3 symbol fill color 7
    s3 symbol fill pattern 0
    s3 symbol linewidth 1.0
    s3 symbol linestyle 1
    s3 symbol char 65
    s3 symbol char font 0
    s3 symbol skip 0
    s3 line type 0
    s3 line linestyle 1
    s3 line linewidth 1.0
    s3 line color 7
    s3 line pattern 1
    s3 baseline type 0
    s3 baseline off
    s3 dropline off
    s3 fill type 0
    s3 fill rule 0
    s3 fill color 1
    s3 fill pattern 1
    s3 avalue off
    s3 avalue type 2
    s3 avalue char size 1.000000
    s3 avalue font 0
    s3 avalue color 1
    s3 avalue rot 0
    s3 avalue format general
    s3 avalue prec 3
    s3 avalue prepend ""
    s3 avalue append ""
    s3 avalue offset 0.000000 , 0.000000
    s3 errorbar on
    s3 errorbar place both
    s3 errorbar color 7
    s3 errorbar pattern 1
    s3 errorbar size 0.180000
    s3 errorbar linewidth 1.0
    s3 errorbar linestyle 0
    s3 errorbar riser linewidth 1.0
    s3 errorbar riser linestyle 0
    s3 errorbar riser clip off
    s3 errorbar riser clip length 0.100000
    s3 comment "dat_qsub/no_pb_x_ginter_intra_I0/cmt.wsk"
    s3 legend  ""
    s4 hidden false
    s4 type xy
    s4 symbol 0
    s4 symbol size 1.000000
    s4 symbol color 7
    s4 symbol pattern 1
    s4 symbol fill color 7
    s4 symbol fill pattern 0
    s4 symbol linewidth 1.0
    s4 symbol linestyle 1
    s4 symbol char 65
    s4 symbol char font 0
    s4 symbol skip 0
    s4 line type 1
    s4 line linestyle 1
    s4 line linewidth 1.5
    s4 line color 7
    s4 line pattern 1
    s4 baseline type 0
    s4 baseline off
    s4 dropline off
    s4 fill type 0
    s4 fill rule 0
    s4 fill color 1
    s4 fill pattern 1
    s4 avalue off
    s4 avalue type 2
    s4 avalue char size 1.000000
    s4 avalue font 0
    s4 avalue color 1
    s4 avalue rot 0
    s4 avalue format general
    s4 avalue prec 3
    s4 avalue prepend ""
    s4 avalue append ""
    s4 avalue offset 0.000000 , 0.000000
    s4 errorbar on
    s4 errorbar place both
    s4 errorbar color 7
    s4 errorbar pattern 1
    s4 errorbar size 1.000000
    s4 errorbar linewidth 1.0
    s4 errorbar linestyle 1
    s4 errorbar riser linewidth 1.0
    s4 errorbar riser linestyle 1
    s4 errorbar riser clip off
    s4 errorbar riser clip length 0.100000
    s4 comment "dat_qsub/no_pb_x_ginter_no_intra_I0/cmt.wsk_set_ct"
    s4 legend  ""
    s5 hidden false
    s5 type xy
    s5 symbol 0
    s5 symbol size 1.000000
    s5 symbol color 11
    s5 symbol pattern 1
    s5 symbol fill color 11
    s5 symbol fill pattern 0
    s5 symbol linewidth 1.0
    s5 symbol linestyle 1
    s5 symbol char 65
    s5 symbol char font 0
    s5 symbol skip 0
    s5 line type 1
    s5 line linestyle 1
    s5 line linewidth 1.5
    s5 line color 11
    s5 line pattern 1
    s5 baseline type 0
    s5 baseline off
    s5 dropline off
    s5 fill type 0
    s5 fill rule 0
    s5 fill color 1
    s5 fill pattern 1
    s5 avalue off
    s5 avalue type 2
    s5 avalue char size 1.000000
    s5 avalue font 0
    s5 avalue color 1
    s5 avalue rot 0
    s5 avalue format general
    s5 avalue prec 3
    s5 avalue prepend ""
    s5 avalue append ""
    s5 avalue offset 0.000000 , 0.000000
    s5 errorbar on
    s5 errorbar place both
    s5 errorbar color 11
    s5 errorbar pattern 1
    s5 errorbar size 1.000000
    s5 errorbar linewidth 1.0
    s5 errorbar linestyle 1
    s5 errorbar riser linewidth 1.0
    s5 errorbar riser linestyle 1
    s5 errorbar riser clip off
    s5 errorbar riser clip length 0.100000
    s5 comment "dat_qsub/no_pb_x_ginter_no_intra_I0/cmt.wsk_set_ct"
    s5 legend  ""
